### ISSUE TITLE
Gracefully handle invalid JSON

### ISSUE THREAD

**Issue by abrudz** [AykutSarac/jsoncrack.com#100]
```
blah
```
gives:
![image](https://user-images.githubusercontent.com/10961427/187087626-011ad083-3bfc-4cf5-b2ab-1dddad48d89d.png)

**Comment by yuvalg99** [comment]
What do you mean by saying "gracefully"?

**Comment by abrudz** [comment]
Say something like "invalid JSON" instead of revealing implementation details.

**Comment by AykutSarac** [comment]
It's handled gracefully on my end 
![Screenshot_20220902-132341_Chrome](https://user-images.githubusercontent.com/47941171/188119680-e7bad94a-860c-42a3-8249-f440ee3e2aa9.jpg)

**Comment by abrudz** [comment]
Ah, it seems to only happen in Firefox. In a Chromium-based browser (Edge), I get the "unexpected token" message.
