### ISSUE TITLE
Dockerfile From node:14-buster as builder

### ISSUE THREAD

**Issue by yjllife** [AykutSarac/jsoncrack.com#135]
docker build  .
Sending build context to Docker daemon 1.468 MB
Step 1/8 : FROM node:14-buster as builder
Error parsing reference: "node:14-buster as builder" is not a valid repository/tag: invalid reference format

need FROM node:14-buster

**Comment by yjllife** [comment]
and has warning

yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @monaco-editor/react@4.4.5" has unmet peer dependency "monaco-editor@>= 0.25.0 < 1".
warning "@monaco-editor/react > @monaco-editor/loader@1.3.2" has unmet peer dependency "monaco-editor@>= 0.21.0 < 1".
warning "react-hot-toast > goober@2.1.10" has unmet peer dependency "csstype@^3.0.10".
warning " > react-zoom-pan-pinch@2.1.3" has incorrect peer dependency "react@^17.0.2".
warning " > react-zoom-pan-pinch@2.1.3" has incorrect peer dependency "react-dom@^17.0.2".
warning "reaflow > rdk > react-scrolllock@5.0.1" has incorrect peer dependency "react@^16.3.0".
warning " > styled-components@5.3.5" has unmet peer dependency "react-is@>= 16.8.0".
warning " > @testing-library/user-event@14.4.2" has unmet peer dependency "@testing-library/dom@>=7.21.4".
warning " > babel-jest@28.1.3" has unmet peer dependency "@babel/core@^7.8.0".
warning "babel-jest > babel-preset-jest@28.1.3" has unmet peer dependency "@babel/core@^7.0.0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax@1.0.1" has unmet peer dependency "@babel/core@^7.0.0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-async-generators@7.8.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-bigint@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-class-properties@7.12.13" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-import-meta@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-json-strings@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-logical-assignment-operators@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-nullish-coalescing-operator@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-numeric-separator@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-object-rest-spread@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-optional-catch-binding@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-optional-chaining@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-top-level-await@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "next-pwa > babel-loader@8.2.5" has unmet peer dependency "@babel/core@^7.0.0".
warning "next-pwa > babel-loader@8.2.5" has unmet peer dependency "webpack@>=2".
warning "next-pwa > clean-webpack-plugin@4.0.0" has unmet peer dependency "webpack@>=4.0.0 <6.0.0".
warning "next-pwa > terser-webpack-plugin@5.3.3" has unmet peer dependency "webpack@^5.1.0".
warning "next-pwa > workbox-webpack-plugin@6.5.4" has unmet peer dependency "webpack@^4.4.0 || ^5.9.0".

[4/4] Building fresh packages...



It's too difficult for me. Can you directly make the completed docker image?

**Comment by eveadam0606** [comment]
I have the same problem as you, do you found solution? @yjllife

**Comment by eveadam0606** [comment]
> and has warning
> 
> yarn install v1.22.19 [1/4] Resolving packages... [2/4] Fetching packages... [3/4] Linking dependencies... warning " > @monaco-editor/react@4.4.5" has unmet peer dependency "monaco-editor@>= 0.25.0 < 1". warning "@monaco-editor/react > @monaco-editor/loader@1.3.2" has unmet peer dependency "monaco-editor@>= 0.21.0 < 1". warning "react-hot-toast > goober@2.1.10" has unmet peer dependency "csstype@^3.0.10". warning " > react-zoom-pan-pinch@2.1.3" has incorrect peer dependency "react@^17.0.2". warning " > react-zoom-pan-pinch@2.1.3" has incorrect peer dependency "react-dom@^17.0.2". warning "reaflow > rdk > react-scrolllock@5.0.1" has incorrect peer dependency "react@^16.3.0". warning " > styled-components@5.3.5" has unmet peer dependency "react-is@>= 16.8.0". warning " > @testing-library/user-event@14.4.2" has unmet peer dependency "@testing-library/dom@>=7.21.4". warning " > babel-jest@28.1.3" has unmet peer dependency "@babel/core@^7.8.0". warning "babel-jest > babel-preset-jest@28.1.3" has unmet peer dependency "@babel/core@^7.0.0". warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax@1.0.1" has unmet peer dependency "@babel/core@^7.0.0". warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-async-generators@7.8.4" has unmet peer dependency "@babel/core@^7.0.0-0". warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-bigint@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0". warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-class-properties@7.12.13" has unmet peer dependency "@babel/core@^7.0.0-0". warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-import-meta@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0". warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-json-strings@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0". warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-logical-assignment-operators@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0". warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-nullish-coalescing-operator@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0". warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-numeric-separator@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0". warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-object-rest-spread@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0". warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-optional-catch-binding@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0". warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-optional-chaining@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0". warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-top-level-await@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0". warning "next-pwa > babel-loader@8.2.5" has unmet peer dependency "@babel/core@^7.0.0". warning "next-pwa > babel-loader@8.2.5" has unmet peer dependency "webpack@>=2". warning "next-pwa > clean-webpack-plugin@4.0.0" has unmet peer dependency "webpack@>=4.0.0 <6.0.0". warning "next-pwa > terser-webpack-plugin@5.3.3" has unmet peer dependency "webpack@^5.1.0". warning "next-pwa > workbox-webpack-plugin@6.5.4" has unmet peer dependency "webpack@^4.4.0 || ^5.9.0".
> 
> [4/4] Building fresh packages...
> 
> It's too difficult for me. Can you directly make the completed docker image?

I suffer the same problem, I solve this problem by build again

**Comment by guitar-etc** [comment]
> docker build . Sending build context to Docker daemon 1.468 MB Step 1/8 : FROM node:14-buster as builder Error parsing reference: "node:14-buster as builder" is not a valid repository/tag: invalid reference format
> 
> need FROM node:14-buster

I was able to build the image right away. Your error could be because the docker version is too low.
