### ISSUE TITLE
Display issue on iPadOS and iOS - all fields show on same line

### ISSUE THREAD

**Issue by jpollard-cs** [AykutSarac/jsoncrack.com#139]
### Issue description

![EC376104-88AF-49AB-95D5-08618F24CE5D](https://user-images.githubusercontent.com/16087487/188317825-d1e250d3-fe37-4aa8-bfa2-b6ec7569a076.jpeg)

Fields are showing on the same line on iPad and iPhone. This behavior is consistent across browsers I tested: Safari, Chrome and Brave (all latest versions including latest OS versions). I’ll attempt to submit a fix if I can find the time tonight.

### Operating system

- OS: iOS and iPadOS (latest)
- Browser: Chrome, Safari, Brave (all latest)

### Priority this issue should have

Low (slightly annoying)

**Comment by AykutSarac** [comment]
Thanks for reporting, the issue seems to occur only on Safari. I'm working on a fix currently.

**Comment by AykutSarac** [comment]
It should be fixed, can you confirm @jpollard-cs?

**Comment by AykutSarac** [comment]
Search node doesn't seem to work correctly, I will close the issue once it gets resolved.

**Comment by jpollard-cs** [comment]
Looking good!
