### ISSUE TITLE
[BUG]: object member and array of one object member have same visual results

### ISSUE THREAD

**Issue by levalup** [AykutSarac/jsoncrack.com#140]
### Issue description

Using JSON:
```json
{
  "A": {
    "A": true
  },
  "B": [
    {
      "A": true
    }
  ]
}
```
at [https://jsoncrack.com/editor](https://jsoncrack.com/editor)

gives:

<img width="677" alt="image" src="https://user-images.githubusercontent.com/8901217/188413040-fc33c890-67eb-4b99-926e-7d7a96a84c3e.png">

As `A` and `B` are different at all.

### Operating system

- OS: macOS Monterey 12.5.1
- Browser: Safari 15.6.1 (17613.3.9.1.16)

### Priority this issue should have

Low (slightly annoying)

**Comment by AykutSarac** [comment]
I'm open for suggestions.

**Comment by levalup** [comment]
S1. May add symbol [] or {} to tell which type it is. Like:
<img width="677" alt="188413040-fc33c890-67eb-4b99-926e-7d7a96a84c3e" src="https://user-images.githubusercontent.com/8901217/190133848-cfca3ceb-b984-454c-85b8-93971fe46b75.png">

**Comment by levalup** [comment]
May add symbol [] and {} to tell which type it is. like:
<img width="677" alt="188413040-fc33c890-67eb-4b99-926e-7d7a96a84c3e" src="https://user-images.githubusercontent.com/8901217/190134204-ff2fd105-6c8a-4a47-b1c0-ea93167a6f48.png">

<img width="677" alt="188413040-fc33c890-67eb-4b99-926e-7d7a96a84c3e" src="https://user-images.githubusercontent.com/8901217/190134172-4d504e9f-5f5f-477d-846c-3f865cddb491.png">

**Comment by jonasmateus** [comment]
I´ve been testing the code and I don´t know how to do that. Cause I have to check each key of json for check if it´s an array or object, doing this I put string **square** or **curly** brackets. The square element `<TextNode/>` receives a property called `text` representing the displayed content.
