### ISSUE TITLE
Build VScode extension

### ISSUE THREAD

**Issue by dylandifilippo** [AykutSarac/jsoncrack.com#142]
### Feature

It would be great to have your tool embedded in VSCODE

**Comment by caopuzheng** [comment]
is there a way to support specific issue, to prioritize the implementation? That would be helpful here

**Comment by guitrocha** [comment]
Up

**Comment by AykutSarac** [comment]
Join JC's Discord server if you're into collaboration with developing VS Code extension https://discord.gg/yVyTtCRueq

**Comment by fatihaziz** [comment]
I'm in! Let's go!!

**Comment by AykutSarac** [comment]
Hello guys! VS Code extension is currently in progress, you may test it out here! https://github.com/AykutSarac/jsoncrack-vscode
Looking forward to see your contributions!

**Comment by Hexrt** [comment]
> Hello guys! VS Code extension is currently in progress, you may test it out here! https://github.com/AykutSarac/jsoncrack-vscode Looking forward to see your contributions!

Exciting start🎉
