### ISSUE TITLE
[BUG]: The child nodes of the same parent are rendered at different levels

### ISSUE THREAD

**Issue by codetiger** [AykutSarac/jsoncrack.com#143]
### Issue description

The child fields of the same parent are rendered at different levels.

Sample JSON
<img width="210" alt="json" src="https://user-images.githubusercontent.com/615337/189051944-69ffec7b-824b-447d-8722-54ee1e838803.png">

Current Render
<img width="397" alt="tree" src="https://user-images.githubusercontent.com/615337/189052345-f769487d-da0f-4178-88e5-80b5f3ab30ab.png">

The field "child3" looks like a child node of "child1,child2" which is not correct.

### Operating system

- OS: macOS Monterey:
- Browser: Safari

- Any other details...

### Priority this issue should have

Low (slightly annoying)

**Comment by AykutSarac** [comment]
To display parents like arrays and objects that is the intended behaviour, what would be the expected behaviour in this case?

**Comment by codetiger** [comment]
My expectation is something like the below diagram

![image](https://user-images.githubusercontent.com/615337/189081322-d9659658-2067-444d-8746-c5ae545aa515.png)

Please ignore the alignment in the image

**Comment by AykutSarac** [comment]
I see similar comments about it, however it will directly impact negatively when visualizing huge json files. Though current one may not reflect what exactly the data is, it illustrates in a better way in general.
