### ISSUE TITLE
JSONC support

### ISSUE THREAD

**Issue by techlake** [AykutSarac/jsoncrack.com#145]
### Feature

Many of the complex JSON I deal with are JSON with comments. The parsers used by many solutions support that extension. Any chance of supporting it? I'm OK if you simply ignore (filter-out) the comments. Obviously, I could write a script which removes the comments. In PowerShell (my preferred tool) I would simply use:
Get-Content .\my-file.jsonc | ConvertFrom-Json -Depth 100 | ConvertTo-Json -Depth 100 | Out-File .\my-plain-json-file.json

**Comment by jpollard-cs** [comment]
I like this idea, as well, even if just to put in the JSON itself and not the visualization as a start as I believe this would make the tool more useful for modeling

**Comment by AykutSarac** [comment]
It could be added, for anyone who would like to work on it please make sure the share link is working.

**Comment by VladCuciureanu** [comment]
I'll take this one.
