### ISSUE TITLE
Python API

### ISSUE THREAD

**Issue by MinuraPunchihewa** [AykutSarac/jsoncrack.com#146]
### Feature

First off, thank you for developing this awesome product! This is really cool. What I would love to have though, is a Python package that does the exact same thing. I believe this will be extremely useful, especially since Python has now become the standard for data processing operations on structures like JSON.

I feel that this can be incorporated into simple Python scripts, but also complex data engineering pipelines that looks to parse JSON data.

### Other context

I could give this implementation a shot, if that is alright!

**Comment by AykutSarac** [comment]
Open for contributions, but not something that I can do right now 🙂
