### ISSUE TITLE
Support JSON path to file from the URL

### ISSUE THREAD

**Issue by GAS85** [AykutSarac/jsoncrack.com#149]
### Feature

I would like to open a JSON file via the Path in URL. E.g. I have my JSON under `https://FQDN/myCoolService/swagger.json`. Instead of open it and copy / paste to the Jsoncrack editor I would like to provide path to it. E.g.:

`https://jsoncrack.com/editor?url=https://FQDN/myCoolService/swagger.json`

Or

`https://jsoncrack.com/editor?url=https://FQDN/api/catalog/spec/56eb8b40-ff74-4712-bc17-d89bb591943c?format=json`

Similar Feature supported by swagger editor, e.g. open Gotify JSON in editor via: https://editor.swagger.io/?url=https://raw.githubusercontent.com/gotify/server/v2.1.5/docs/spec.json

### Alternative solutions or implementations

Current solution similar to plantUML, where I should provide JSON in a URL, but this has length limits and suitable for a bigger JSONs.

```
https://jsoncrack.com/editor?json=[[%22squadName%22%2C%22homeTown%22%2C%22formed%22%2C%22secretBase%22%2C%22active%22%2C%22members%22%2C%22a|0|1|2|3|4|5%22%2C%22Super%20hero%20squad%22%2C%22Metro%20City%22%2C%22n|WW%22%2C%22Super%20tower%22%2C%22b|T%22%2C%22name%22%2C%22age%22%2C%22secretIdentity%22%2C%22powers%22%2C%22a|C|D|E|F%22%2C%22Molecule%20Man%22%2C%22n|T%22%2C%22Dan%20Jukes%22%2C%22Radiation%20resistance%22%2C%22Turning%20tiny%22%2C%22Radiation%20blast%22%2C%22a|K|L|M%22%2C%22o|G|H|I|J|N%22%2C%22Madame%20Uppercut%22%2C%22n|d%22%2C%22Jane%20Wilson%22%2C%22Million%20tonne%20punch%22%2C%22Damage%20resistance%22%2C%22Superhuman%20reflexes%22%2C%22a|S|T|U%22%2C%22o|G|P|Q|R|V%22%2C%22Eternal%20Flame%22%2C%22n|4C92%22%2C%22Unknown%22%2C%22Immortality%22%2C%22Heat%20Immunity%22%2C%22Inferno%22%2C%22Teleportation%22%2C%22Interdimensional%20travel%22%2C%22a|a|b|c|d|e%22%2C%22o|G|X|Y|Z|f%22%2C%22a|O|W|g%22%2C%22o|6|7|8|9|A|B|h%22]%2C%22i%22]
```

Also there is UI functionality to open JSON via URL.

### Other context

Or maybe I simply do not know how to do it...

**Comment by reidca** [comment]
This feature would also allow the sharing of large json files. 

Currently when you share a link to json crack it seems that the json data is base64 encoded and included in the url string.  This is limited to 5000 characters which is pretty small.

Why not have a feature where you can load the editor from an existing json file url (as per this suggestion) which would allow embedding of the editor in websites for large files.

**Comment by msdrigg** [comment]
I was also looking for this

**Comment by eabeliuk** [comment]
I was also looking for this. The limit of 5000 characters is pretty small.

**Comment by eabeliuk** [comment]
@AykutSarac , any updates about this ticket, or plans to work on it in the near future? Thanks!

**Comment by AykutSarac** [comment]
> @AykutSarac , any updates about this ticket, or plans to work on it in the near future? Thanks!

Hi there, it's currently live with v2.5.0 you can check it out here: https://jsoncrack.com/docs
