### ISSUE TITLE
Error: failed to download 

### ISSUE THREAD

**Issue by drvgautam** [AykutSarac/jsoncrack.com#150]
### Issue description

 While rendering a LARGE json file, it failed to download the rendered png image with an error message [failed to download]

### Operating system

- Browser [Firefox]:

### Priority this issue should have

Medium (should be fixed soon)

**Comment by trimalcione** [comment]
What do you mean by large? Is it something replicable?

**Comment by harmeet-1337** [comment]
I also experienced same issue. I tried on firefox and chrome. Length of json is 3007.

**Comment by drvgautam** [comment]
Here's a sample file to reproduce the error.   [json_crack_failedDownload_sample_json.zip](https://github.com/AykutSarac/jsoncrack.com/files/9537939/json_crack_failedDownload_sample_json.zip)

**Comment by trimalcione** [comment]
I can't reproduce the bug on my PC. I suppose it's not properly a bug at this point.
The application does client-side computation, this means that the machine resources required to produce an output, are proportional to the input JSON you enter.

This is the output I got with the file you attached:
![jsoncrack com](https://user-images.githubusercontent.com/17990410/189503076-be68c79e-ed37-4b03-b987-5fce537f4983.png)

I guess the code can be engineerized in some way. For this, I think this issue should be flagged as refactor more than bug.

**Comment by AykutSarac** [comment]
I've done some performance improvements could effect directly on this, however it mostly relies on your computer specs as paint is made on the DOM.
