### ISSUE TITLE
Any plans on creating library support and publishing to npm

### ISSUE THREAD

**Issue by amitsetty** [AykutSarac/jsoncrack.com#151]
I think it would be really powerful to be able to use a JSCrack React Component within other projects

**Comment by Yakumwamba** [comment]
That would be really nice to have I can look into this if there is no one doing it

**Comment by AykutSarac** [comment]
It will be likely to be released when there is the VS Code extension.

**Comment by amitsetty** [comment]
Any idea when this will be?

**Comment by AykutSarac** [comment]
Unfortunately I cannot give an ETA as I'm still new into developing VS Code extension.
