### ISSUE TITLE
Bug: It is not formatting terraform state file

### ISSUE THREAD

**Issue by mohan023** [AykutSarac/jsoncrack.com#153]
### Issue description

The state file contains around 7000 of lines. 
![image](https://user-images.githubusercontent.com/4489345/189471944-953adc03-7205-4b61-b82c-4df6689ee110.png)

### Operating system

- OS: [e.g. iOS]: OS
- Browser [e.g. chrome, safari]: Chrome

- Any other details...

### Priority this issue should have

High (immediate attention needed)

**Comment by AykutSarac** [comment]
You should wait a bit longer than usual while the canvas is rendering when the file is big.

**Comment by alicashelton** [comment]
Ok, let's wait

**Comment by mohan023** [comment]
I waited for 15 mins. But it didn't work. There is no progress bar so that
we know if we should wait more or there is a problem.

**Comment by AykutSarac** [comment]
Can you share the json file?

**Comment by mohan023** [comment]
There is some sensitive data in file. I cannot modify it manually. So I
would not be able to share it.

**Comment by AykutSarac** [comment]
Can you share more details about your OS & specs? Also can you try again, I made some improvements today?

**Comment by mohan023** [comment]
Os is Windows. Browser is chrome. Processor i5. Sure I'll try again today.

**Comment by AykutSarac** [comment]
Assuming the issue is has been resolved now, closing it.

**Comment by mohan023** [comment]
Sure.
