### ISSUE TITLE
[BUG]: Ignore mouse click event after resizing view.

### ISSUE THREAD

**Issue by Hexrt** [AykutSarac/jsoncrack.com#158]
### Issue description

**Use right mouse to resize view**
![right_mouse_move](https://user-images.githubusercontent.com/57286895/189532178-67eafe19-b8c7-42c4-ad44-0edef3f6abc3.gif)
**Use left mouse to resize view when hover the cusor over something "button"**
![left_mouse_move](https://user-images.githubusercontent.com/57286895/189532153-3f4dc7f6-fd66-404a-98f0-290a50aed67c.gif)

### Operating system

- OS: [Windows]:
- Browser [Chrome]:

### Priority this issue should have

Low (slightly annoying)

**Comment by noobyogi0010** [comment]
@AykutSarac 
I would like to work on this issue if no one else has taken it up.
Thanks!

**Comment by Yakumwamba** [comment]
@noobyogi0010 That would be great as I also find it an issue. Thanks!

**Comment by Hexrt** [comment]
> @AykutSarac I would like to work on this issue if no one else has taken it up. Thanks!

That would be great.Thanks!
