### ISSUE TITLE
Support YAML YML

### ISSUE THREAD

**Issue by gabrielpadilh4** [AykutSarac/jsoncrack.com#161]
### Feature

Enable the diagram for other types of format, examples:
- YML
- YAML
- XML

### Alternative solutions or implementations

N/A

**Comment by chipzoller** [comment]
This would be SUPER helpful to visualize very large, complex Kubernetes manifests like CustomResourceDefinitions.

**Comment by asmbatha** [comment]
Yes please. I have just now found another online tool to convert my huge yaml files to json and then pasted it in the jsoncrack editor. Would be really cool if I could just paste yaml directly in. I guess it's not really "json" crack anymore though. But really neat tool. I'd also love it as a browser extension. I'm happy to contribute some code if you're happy with that.

**Comment by LukasGrebe** [comment]
JSON and YAML are fairly close. JSON Schema can be used with YAML and most JSON ist valid YAML. i Suppose the name jsoncrack would thus still be valid.


> JSON Schema can be used to validate YAML documents. [YAML Ain't Markup Language (YAML)](http://yaml.org/) is a powerful data serialization language that aims to be human friendly. **Most JSON is syntactically valid YAML**, but idiomatic YAML follows very different conventions. While YAML has advanced features that cannot be directly mapped to JSON, most YAML files use features that can be validated by JSON Schema. JSON Schema is the most portable and broadly supported choice for YAML validation.

https://json-schema-everywhere.github.io/yaml

**Comment by chipzoller** [comment]
This was closed as completed. Which PR adds support for YAML in that case?

**Comment by AykutSarac** [comment]
There's currently no YAML support at JSON Crack, however I'd recommend keeping an eye at the [herowand.com](https://herowand.com), as I'm planning to release a new advanced editor soon will support multiple languages.

**Comment by chipzoller** [comment]
Ok, so this issue should be closed as "not planned" instead.

**Comment by AykutSarac** [comment]
See you all here whose subscribed to this issue: https://www.producthunt.com/products/herowand-editor 🚀
