### ISSUE TITLE
[BUG]: Unable to load extremely large json file

### ISSUE THREAD

**Issue by NghiaNguyen170192** [AykutSarac/jsoncrack.com#163]
### Issue description

**Issue description**

1/ Run JSON Crack in Docker. 
![image](https://user-images.githubusercontent.com/4945168/189572749-673f900a-8f41-478a-a48b-bd2f6a283c31.png)

2/Import extremely large JSON file from [url](https://raw.githubusercontent.com/poe-tool-dev/passive-skill-tree-json/1274585e267ea63affdf9103b965e93f9c36b7b8/3.18.0/SkillTree.json)
![image](https://user-images.githubusercontent.com/4945168/189572820-e45fda51-957b-49f2-aded-fe9dbcc7aa59.png)

3/ Unable to display in Editor(Page Unresponsive)
![image](https://user-images.githubusercontent.com/4945168/189572934-09f38e82-a655-4455-8043-1c0bd5c2a18c.png)

### Operating system

- OS: Windows 10
- Browser [e.g. chrome, safari]: Chrome

- Any other details...

### Priority this issue should have

Medium (should be fixed soon)

**Comment by posidron** [comment]
Experienced the same, it will ultimately load (for a decently large JSON blob of ~12mb) but saving the file as image or to clipboard will cause an OOM crash in the renderer process. I thought that may be noteworthy to point out. Thanks for the project, keep it up!

**Comment by NghiaNguyen170192** [comment]
@posidron, yes, I have tested many plugins and text editors with large JSON files and many have failed to load.

**Comment by AykutSarac** [comment]
As everything is handled on the client side and browser, it would not be possible to load such a large JSON file nevertheless performance optimizations. I've made some improvements recently but still it couldn't handle a super large JSON file, at least the recent changes prevent window freezing displays an error now.
