### ISSUE TITLE
Number of elemments in arrays

### ISSUE THREAD

**Issue by carlos-puente** [AykutSarac/jsoncrack.com#169]
### Feature

Will be very useful to see the number of element of each collection, as you can see in the image:

<img src="https://i.ibb.co/d5F4HTz/schreenshot.png"></img>

**Comment by dolev146** [comment]
can you draw a big red arrow and a circle where you want the number of elements to be shown?
cab you also draw a circle of what element to show the number? if you can edit the image so it would have the numbers it will be
more easily understand what you want me to do :)

**Comment by carlos-puente** [comment]
Hello @dolev146 if you see the image attached, the number of elemments are added after the node name (I've edited the sample graph with gimp). You can see in the example:
 members **(3)**, being 3 the number of children 
 or powers **(3)**, being 3 the number of children 
 or powers **(5)**, being 5 the number of children.

**Comment by AykutSarac** [comment]
That's actually a good idea, ideally add an option at settings to turn it off.
