### ISSUE TITLE
[BUG]: When rotated, hidden node showed up. need to "click hide" again to hide it.

### ISSUE THREAD

**Issue by fatihaziz** [AykutSarac/jsoncrack.com#173]
### Issue description

1. Hide a node
2. Rotate
3. Here ther result:
![image](https://user-images.githubusercontent.com/23287658/190569184-19256760-7266-45e5-9594-de54cd3fced7.png)
4. same behaviour, when got rotated again,

### Media & Screenshots

```md
![image](https://user-images.githubusercontent.com/23287658/190569413-da6473fc-8e89-4892-8021-457eff68b29f.png)
```

### Operating system

- OS: Windows
- Browser: Chrome
- Any other details: 
  - Desktop 1920x1240 (maybe)

### Priority this issue should have

Low (slightly annoying)

**Comment by Cool-Runningz** [comment]
Hey 👋🏽 @AykutSarac thanks for creating such a great tool! 
I am interested in working on this. Is this still up for grabs??

**Comment by AykutSarac** [comment]
> Hey 👋🏽 @AykutSarac thanks for creating such a great tool! I am interested in working on this. Is this still up for grabs??

Hello! You can work on it!

**Comment by fatihaziz** [comment]
Thank you guys👍

**Comment by Cool-Runningz** [comment]
Great! Thanks for the opportunity to contribute and I will reach out if I have further questions.

**Comment by Cool-Runningz** [comment]
@AykutSarac I've spent the last day or so trying to familiarize myself with the codebase, however, I'm still a little stuck on where the issue is happening and was hoping you might be able to help me out. My initial hunch is that the `collapsedNodes` are getting reset when the layout is rotated. 

Do you happen to have an idea of where the issue might be surfacing? Or maybe point me to a general location where you think the bug could be occurring. Thank you very much for your time!

**Comment by AykutSarac** [comment]
@Cool-Runningz The issue most likely caused by the key at Graph component. The key value is equals to layout and gets rerendered once it changed.

**Comment by shivam1646** [comment]
@AykutSarac I've created PR #238 to fix this issue. Could you please take a look when you get some time.

**Comment by Cool-Runningz** [comment]
Well, it looks like I didn't move quickly enough. I guess that's how it goes in open-source sometimes 🤷🏽‍♀️ . 
@AykutSarac Thanks anyway for the opportunity to work on this and great work with JSON Crack. It's a really cool project!

**Comment by fatihaziz** [comment]
Even me cannot comprehend the solution is really simple and really few line of codes. 🤣
