### ISSUE TITLE
Option to install locally, as a Visual Studio (or Eclipse) Plugin

### ISSUE THREAD

**Issue by intltechventures** [AykutSarac/jsoncrack.com#177]
### Feature

To provide an optimal user experience, it would be very beneficial if this was available as a plugin for installation in Visual Studio or Eclipse...without needing to context switch to an instance running in a Docker container.
For security reasons, pasting JSON into an external web site would be a no-go for most organizations.

**Comment by AykutSarac** [comment]
Is this what you're looking for? https://github.com/AykutSarac/jsoncrack-vscode

**Comment by intltechventures** [comment]
Closing this - as I didn't spot that there is already a pre-release project underway
https://github.com/AykutSarac/jsoncrack-vscode
