### ISSUE TITLE
performance improvements

### ISSUE THREAD

**Issue by arthurboss** [AykutSarac/jsoncrack.com#185]
### Feature

Amazing tool!! Great work team! 

I'd like to share that I tested with a JSON with 53k+ lines (which is an API response used by my company 🤯 ) and it gets a big hit on performance on client side (my browser literally froze and it didn't work. Tried 3 times). 
Considering how useful **json.crack** is for the community, it'd be great to have a look on how to improve performance so it does not limit its usage.

### Alternative solutions or implementations

I highly recommend you to check [web assembly](https://webassembly.org/).

If you're not familiar with it, these are things to keep in mind:
- it's possible to only write the chunk of code that does the processing in web assembly
- it's browser native
- there's no need to use a different language to use web assembly, which makes it easier to try it out

One good intro video on it: https://youtu.be/HktWin_LPf4

**Comment by AykutSarac** [comment]
Can you try now and let me know if anything has changed?

**Comment by arthurboss** [comment]
> Can you try now and let me know if anything has changed?

Tried again and at least now the issue is handled!! Pretty cool!!

<img width="493" alt="Screenshot 2022-09-28 at 15 37 24" src="https://user-images.githubusercontent.com/37892811/192793453-3ff17d11-9541-44da-b55a-1e33180f19eb.png">

Regardless, hope you can get to improving the performance at some point! As I said, this is an amazing and useful tool!! 

Whenever I get a proper time I'll look into it and hopefully open a PR with my suggestion as well.
