### ISSUE TITLE
[BUG]: Failing to download image with json > 1500 lines

### ISSUE THREAD

**Issue by lays147** [AykutSarac/jsoncrack.com#187]
### Issue description

1. Paste a json that has more than 1500 lines
2. Try to download or copy to clipboard
3. Action fails

The editor loads and render the json successfully, the problem happens when I try to download it.
There's no log on the console.
![Screenshot_20220920_155321](https://user-images.githubusercontent.com/7799231/191340937-02b93783-ab7f-40b0-909a-596e7fd03d9f.png)

### Operating system

- OS: Manjaro Linux
- Browser: Firefox

Note: The error does not happen on Chromium.

### Priority this issue should have

Low (slightly annoying)

**Comment by AykutSarac** [comment]
It's working fine on my end, would it be possible for you to share the JSON file here?
