### ISSUE TITLE
[BUG]: Change web domian name. Many firewall have "crack" as a banned word

### ISSUE THREAD

**Issue by JavierPozoDelevoper** [AykutSarac/jsoncrack.com#189]
### Issue description

Hi,

This tool is very powerfull and i will use it from website. But in my work we used vpn and security rules have many word forbidden for example "crack".

Is it possible to change the domain name of the web?

Thx

### Priority this issue should have

Low (slightly annoying)

**Comment by AykutSarac** [comment]
I have to admit current name sucks, unfortunately it's too late to change name again right now.
