### ISSUE TITLE
Diagram UI Node Hiding Parity With Editor

### ISSUE THREAD

**Issue by ciscorucinski** [AykutSarac/jsoncrack.com#190]
### Feature

I've noticed that there isn't feature parity with respect to hiding nodes of the diagram UI. The code editor allows users to hide 8 different items, but the diagram UI only allows the hiding of 4 items from the Super Hero Squad sample.

Every item in the lists should be able to be hidden

### Alternative solutions or implementations

I'm not sure if this is implemented, but if individual list items were available, the diagram should allow for the re-rendering of a more condensed view.

In the Super Hero Squad sample, I noticed that the diagram doesn't get condensed when you hid the "powers" for "Madame Uppercut". When clicked on the hide button the first time, I was expecting a more condensed view.

### Other context

![Screenshot from 2022-09-22 07-26-20](https://user-images.githubusercontent.com/8707125/191621642-efed3e16-afd8-44cd-8ca5-6362afa17460.png)

**Comment by AykutSarac** [comment]
This will cause the graph to re-render and it will become a performance issue when larger JSON is transformed onto graph. Thus for each toggle hide it will take lots of time, but I'm open to suggestions.
