### ISSUE TITLE
Focus on Node through JSON editor navigation

### ISSUE THREAD

**Issue by firedev** [AykutSarac/jsoncrack.com#192]
### Feature

I would like have the graph to be centered on the node I am clicking in JSON. 

Right now it's a bit hard to view larger documents as they take too much space.

**Comment by AykutSarac** [comment]
Current behaviour of clicking node is opens Node Content modal, we should decide one of the between.

**Comment by guitar-etc** [comment]
@AykutSarac I think you misread. @firedev wants to click somewhere in JSON and expects the screen to automatically scroll to the corresponding node.

**Comment by jazzyclimber** [comment]
Not sure how active this is. But an alternative -- which would also be just as dope if not more so would be the ability to edit the node directly from the tree view. I think this feature would make this plugin/app wildly more popular and useful.
