### ISSUE TITLE
[BUG]: Siblings look like descendents

### ISSUE THREAD

**Issue by danellis** [AykutSarac/jsoncrack.com#193]
### Issue description

The screenshot is from the following JSON:

```json
{
  "timestamp": "...",
  "products": [
    {
      "id": "...",
      "attributes": {
        "price": "9.99",
        "title": "..."
      }
    },
    {
      "id": "...",
      "attributes": {
        "price": "23.48",
        "title": "..."
      }
    }
  ]
}
```

As you can see, the graph makes it look like `products` is a child node of `timestamp`. They should be shown as side-by-side like the two `id` nodes are.

### Media & Screenshots

```md
https://imgur.com/RBxCgg2
```

### Priority this issue should have

Medium (should be fixed soon)

**Comment by Tonystark423** [comment]
I agree 💯

**Comment by AykutSarac** [comment]
In this case there should be a root empty node connecting to `timestamps` and `products` and so on for the rest, you are actually right. Open for contributions for this one 🙂

**Comment by hanbin9775** [comment]
Hi! Can I work on this issue?

**Comment by AykutSarac** [comment]
To enhance user readability and understanding array & object keys should be child of the parents, the algorithm was rewritten and improved with #251 that cover this behaviour.

**Comment by hanbin9775** [comment]
Oh, but there's still an issue. 
```
{
  "products": [
    {
      "id": "...",
      "attributes": {
        "price": "9.99",
        "title": "..."
      }
    },
    {
      "id": "...",
      "attributes": {
        "price": "23.48",
        "title": "..."
      }
    }
  ],
"timestamp": "..."
}
```
With this JSON, graph makes empty node. 

<img width="1071" alt="스크린샷 2022-11-24 오후 6 01 03" src="https://user-images.githubusercontent.com/37659866/203739322-e5575973-4c6d-4caa-9e90-03e56c8d7499.png">

It should make same graph in any order of properties.

**Comment by AykutSarac** [comment]
> Oh, but there's still an issue.
> 
> ```
> {
>   "products": [
>     {
>       "id": "...",
>       "attributes": {
>         "price": "9.99",
>         "title": "..."
>       }
>     },
>     {
>       "id": "...",
>       "attributes": {
>         "price": "23.48",
>         "title": "..."
>       }
>     }
>   ],
> "timestamp": "..."
> }
> ```
> 
> With this JSON, graph makes empty node.
> 
> <img alt="스크린샷 2022-11-24 오후 6 01 03" width="1071" src="https://user-images.githubusercontent.com/37659866/203739322-e5575973-4c6d-4caa-9e90-03e56c8d7499.png">
> 
> It should make same graph in any order of properties.

Interesting, I thought it was fixed with #251

**Comment by hanbin9775** [comment]
Are you going to re-open this issue or should I just open a new one?
And if it's ok, I want to create pr for this issue.

**Comment by AykutSarac** [comment]
> Are you going to re-open this issue or should I just open a new one? And if it's ok, I want to create pr for this issue.

I appreciate it.

**Comment by Tonystark423** [comment]
If you would be so kind as to reopen it, I don't mind you getting the pr if that's what you are looking for

**Comment by hanbin9775** [comment]
@Tonystark423 I opened new issue #266 and yes I created PR #268 for the issue. Thanks.
