### ISSUE TITLE
[BUG]: export png is blurry and unreadable compared to web UI

### ISSUE THREAD

**Issue by IsraelTorresSM** [AykutSarac/jsoncrack.com#194]
### Issue description

1. Import JSON file export from VirusTotal API response - 429 KB (439,660 bytes), 9365 lines (ref: detailed-10-2022-09-16 - crack-redact.json - zipped as detailed-10-2022-09-16 - crack-redact.zip)
2. JSON shows to be valid and all appears well in web UI (ref: 0-webUI.PNG)
3. Export to PNG (Save) (default Transparent background) (ref: 1-file-export.png)
4. Receive a wait message box, but let it go and eventually receive downloaded png 3.85 MB (4,044,112 bytes) 1,383 x 16,384
5. Open PNG in image viewer and zoom in, all items blurry and unreadable. (opened in different image viewer software to test) (ref: 2-zoom-1.PNG), (ref: 3-zoom-2.PNG)
![0-webUI](https://user-images.githubusercontent.com/103773332/191856548-c3918d79-2f02-4e90-842c-226c506b707b.PNG)
![2-zoom-1](https://user-images.githubusercontent.com/103773332/191856551-bffe1ca8-f355-4c18-ad09-c2015120a0ed.PNG)
![3-zoom-2](https://user-images.githubusercontent.com/103773332/191856556-6ce5bb21-aff9-45ae-bbd7-de168d53bb55.PNG)
![1-file-export](https://user-images.githubusercontent.com/103773332/191856558-a4e10c99-daae-4a25-9cc9-08247ea6bbc1.png)
[detailed-10-2022-09-16 - crack-redact.zip](https://github.com/AykutSarac/jsoncrack.com/files/9629589/detailed-10-2022-09-16.-.crack-redact.zip)

### Operating system

- OS: Windows 10 Pro
- Browser : Google Chrome Version 105.0.5195.127 (Official Build) (64-bit)

### Priority this issue should have

Medium (should be fixed soon)

**Comment by dogukanuhn** [comment]
https://github.com/AykutSarac/jsoncrack.com/pull/204

**Comment by AykutSarac** [comment]
Added "SVG" option with #309
