### ISSUE TITLE
Feature suggestion: visualisation of repeated values

### ISSUE THREAD

**Issue by agrath** [AykutSarac/jsoncrack.com#197]
Feel free to close this if it doesn't fit into your design for this tool

I *love* this - one thing that could be handy, though it would need to be toggled (able to switch on/off) is to be able to collapse repeated sub-tree values at the same depth into a separate list with duplicates removed. For example, if two heroes had the same power, each power would only display once - allowing you to visualise that clearly. Similar to how a database can have a foreign key. 

I think that both the current way of display and this way would need to be used in tandem though, since this suggestion is an interpretation of the data, rather than a visualisation of the graph.

Understand if this is out of scope or not a desired feature.

**Comment by AykutSarac** [comment]
Thanks for sharing your idea, I think this is currently out of scope as this is a too specific case for a visualization tool :)
