### ISSUE TITLE
[BUG]: Cannot reliably zoom out on the large JSON

### ISSUE THREAD

**Issue by alllex** [AykutSarac/jsoncrack.com#202]
### Issue description

Steps to reproduce:
1. Open a large JSON file
2. Try zooming out as much as possible

Current behavior:
The UI does not allow zooming out with the mouse wheel after a certain point at all.
If using a trackpad, then zooming out slightly more is possible, however the UI forcefully zooms back in.
Additionally, when zooming out to the maximum, the whole graph can become inverted vertically (the Y axis is flipped). This includes the text written in the boxes.

Expected behavior:
It is possible to zoom out smoothly (without jumps) at least until the whole graph is visible on the screen.
However, I think it would be even better if I could zoom out slightly further so there is some empty space left around the whole graph.

I this tool as being very useful, however, I am mostly interested in viewing very large files. Interestingly, the tool and the browser has no problem at all processing a big JSON, but the UI currently makes it impossible to navigate this big graph.

### Media & Screenshots

https://user-images.githubusercontent.com/2759152/192013438-17ad4b56-28c7-4dfc-ab20-9e5a5f1a25dc.mp4

### Operating system

- OS: macOS 12.4
- Browser: Chrome

### Priority this issue should have

Medium (should be fixed soon)

**Comment by AykutSarac** [comment]
You're right that zooming and centering is not working correctly, what I'm thinking about this is to calculate the width of canvas and set a max zoom proportional on it.

**Comment by AykutSarac** [comment]
@alllex I've just pushed an update can you try it after a few minutes and share your feedback?

**Comment by AykutSarac** [comment]
Apparently it broke the zoom, I reverted back changes and set maxZoom to 0.25 instead.

**Comment by alllex** [comment]
Thank you for the quick response!

I am not sure if the last changes were supposed to fix the issue or just revert to previous behavior.

I now tried the zooming again after a hard page reload and also in Incognito to make sure I get the fresh build (if it was deployed). The issue is still present for me.

Maybe, it's now possible to zoom out a bit further, but it's not enough to see the whole graph:

https://user-images.githubusercontent.com/2759152/192051310-db12ef4c-e51b-40b3-b2c5-cd5c4389e918.mov
