### ISSUE TITLE
Support large json files

### ISSUE THREAD

**Issue by lsiem** [AykutSarac/jsoncrack.com#205]
### Feature

JSON Crack is currently not yet able to visualize larger JSON files. This would be of great advantage in my opinion, as these are usually the most difficult to understand without visualization.

**Comment by AykutSarac** [comment]
Supporting large JSON files is more about meeting requirements than a choice.  This warning is displayed for files over the current application's capacity.

**Comment by lsiem** [comment]
Is there a way to disable this limitation if you host the application yourself?

**Comment by AykutSarac** [comment]
> Is there a way to disable this limitation if you host the application yourself?

Search for 8_000 and remove the line, it should work but window will probably crash when it couldn't handle the file.

**Comment by lsiem** [comment]
> > Is there a way to disable this limitation if you host the application yourself?
> 
> Search for 8_000 and remove the line, it should work but window will probably crash when it couldn't handle the file.

Then the feature suggestion that the application can handle large JSON files would be one after all?

**Comment by lsiem** [comment]
The graph is loaded on a very large JSON file, however I get an `Error code: Out of Memory` when I try to save the graph as an image.
