### ISSUE TITLE
[Feature Request] 2 possible new features

### ISSUE THREAD

**Issue by fabriziodidthis** [AykutSarac/jsoncrack.com#206]
### Feature

1 - allow me to edit the node content. 
Whenever I click in the node, I could be able to edit the node content, where the JSON content, of course, would be changed as soon I click in a Save button in the modal

2 - jump to the corresponding line whenever I click in a node
When I click in a node, the app would show me the line in the JSON and the same would be applied if I click in any line in the json file. And if I edit the content in json, this change should be reflected in the nodes.

**Comment by AykutSarac** [comment]
Both are acceptable and could be added individually. Adding "confirmed" label.

**Comment by santoni0** [comment]
Hello, could I get assigned to this issue?

**Comment by VladCuciureanu** [comment]
Number 1 has an open PR at #147

**Comment by AykutSarac** [comment]
Editing through graph has been added now, there is another issue for second one so I'm closing it.
