### ISSUE TITLE
Store current JSON in local storage

### ISSUE THREAD

**Issue by evandrmb** [AykutSarac/jsoncrack.com#208]
### Feature

It would be helpful if the website could store the last typed JSON in local storage, so we wouldn't need to retype it whenever the browser closes.

**Comment by aditya-shelke99** [comment]
Hey there, Can I work on this issue and create a PR ? 
I think I have to store the complete json in browsers local storage and reset the current json(with the locally stored json) whenever a new tab is opened

**Comment by Tonystark423** [comment]
Ygxax

**Comment by adi-uchiha** [comment]
@AykutSarac Hava look at this. Tell me if this needs any changes

**Comment by AykutSarac** [comment]
Thanks for the idea, currently it's out of the plan but might consider in the future.
