### ISSUE TITLE
[BUG]: Issue launching docker container locally

### ISSUE THREAD

**Issue by DarrenC** [AykutSarac/jsoncrack.com#212]
### Issue description

Hello, 

After building the docker image and running locally as per the README, I had the following error: 

> [emerg] 1#1: open() "/etc/nginx/conf.d/default.conf" failed (13: Permission denied) in /etc/nginx/nginx.conf:36

It looks like on linux systems, docker copies files with owner/group as root:root. 

I could workaround it by adding --chown option to the Dockerfile to make the owner the same as the container user:

`COPY --chown=nginx:root default.conf /etc/nginx/conf.d/default.conf`

Is this a bug?

### Operating system

- OS: Ubuntu 20.04

### Priority this issue should have

Low (slightly annoying)

**Comment by andreagrax** [comment]
Same issue also on OSX.
Proposed fix works

**Comment by nnamua** [comment]
I also hat the same permission issues with the files in the `assets/` directory (favicon, font). Fixed it with by explicity setting the user here aswell `COPY --from=builder --chown=nginx:root /src/out /app`.
