### ISSUE TITLE
integrate with monaco editor

### ISSUE THREAD

**Issue by GlauberF** [AykutSarac/jsoncrack.com#219]
### Feature

is there a way to integrate with monaco editor (https://microsoft.github.io/monaco-editor/) ?
would you have an example?

**Comment by AykutSarac** [comment]
What do you mean, JSON Crack currently using monaco editor?

**Comment by GlauberF** [comment]
yes

**Comment by dudarau** [comment]
@GlauberF the editor is already integrated, do you miss some functionality of the editor?

**Comment by GlauberF** [comment]
@dudarau perfect, how do I use it, documentation?
how to instantiate?

**Comment by dudarau** [comment]
@GlauberF  here is the JSONcrack editor example [https://jsoncrack.com/editor](https://jsoncrack.com/editor)
The left part(with line numbers and JSON data) is implemented based on the Monaco editor. 

You can run the same locally, just clone this repo, and run the next commands: 
```
yarn
yarn dev
```
now it's available on [localhost:3000/editor](http://localhost:3000/editor)
