### ISSUE TITLE
Understanding character limit for sharing

### ISSUE THREAD

**Issue by josecolella** [AykutSarac/jsoncrack.com#224]
### Feature

Trying to understand what the limit for sharing large JSON is. Could we leverage local storage for persisting this and have a unique identifier as the key to the JSON value.

<img width="585" alt="image" src="https://user-images.githubusercontent.com/1974588/193897315-5be3e4ab-717a-4719-890f-e3b5a0905f43.png">

**Comment by AykutSarac** [comment]
The limit is for the browser to handle. Test with longer link by increasing the length yourself and going to the link, you will see it doesn't accept longer links at some certain limit somewhat near to 5000.

**Comment by GAS85** [comment]
This could be solved with #149

**Comment by AykutSarac** [comment]
> This could be solved with #149

I'll go on with this as a solution to the issue.
