### ISSUE TITLE
Edit on the displayed drawing

### ISSUE THREAD

**Issue by Huyueeer** [AykutSarac/jsoncrack.com#232]
### Feature

Can you support editing in a node of the generated graph

**Comment by theogainey** [comment]
Hi I opened a [PR](https://github.com/AykutSarac/jsoncrack.com/pull/228) for this. It has not yet been merged. If you see any issues with it please let know and I can get them fixed.

**Comment by ACERY1** [comment]
Need this feature very much

**Comment by AykutSarac** [comment]
This has been added now.
