### ISSUE TITLE
[Feature Request] Fix Json 

### ISSUE THREAD

**Issue by Hugocorreaa** [AykutSarac/jsoncrack.com#239]
### Feature

Is there a way to add a **fix json** like in this site? [https://jsonformatter.curiousconcept.com/](url)

It will repairs common JSON errors like replacing incorrect quotes, adding missing quotes, correcting numeric keys, lowercasing literals, escaping unescaped characters, and removing comments and trailing commas.

**Comment by AykutSarac** [comment]
I think keeping the app single-purpose and reducing the amount of features in this matter would be better in long term. Thanks for sharing idea! 🙂
