### ISSUE TITLE
Collapse bug

### ISSUE THREAD

**Issue by AykutSarac** [AykutSarac/jsoncrack.com#241]
@AykutSarac The bug is present on `production` and is unrelated to this ticket.
I suggest opening a new issue for this bug.

https://user-images.githubusercontent.com/71708164/194141356-fcf6c181-f830-42a6-b5e7-49fcb3b77532.mov

You can reproduce it by using this JSON:

`{
  "test": "test",
  "members": [
    {
      "test": "test",
      "members": [
        {
          "test": "test",
          "members": [
            {
              "test": "test",
              "members": []
            }
          ]
        }
      ]
    }
  ]
}
`

_Originally posted by @VladCuciureanu in https://github.com/AykutSarac/jsoncrack.com/issues/230#issuecomment-1268835382_

**Comment by mintbomb27** [comment]
Hey! I'd like to work on this!

**Comment by mintbomb27** [comment]
@AykutSarac Is the expected working of this issue to expand all the children, or just expand till the next level of the graph?

**Comment by VladCuciureanu** [comment]
@mintbomb27 
1. Use this json (or any depth >= 4 json):
`
{ "test": "test", "members": [ { "test": "test", "members": [ { "test": "test", "members": [ { "test": "test", "members": [] } ] } ] } ] }
`
2. Close the graph nodes one by one, from leaf to root
3. Expand the first node

At this point, in the video at 0:04, you can see other nodes appear besides the expected one (the disconnected node is not expected)

**Comment by shivam1646** [comment]
@AykutSarac I've created PR #243  to fix this issue. Could you please take a look when you get some time.
