### ISSUE TITLE
[BUG]: Autoformat moves to the bottom of the Line

### ISSUE THREAD

**Issue by Maduki-tech** [AykutSarac/jsoncrack.com#246]
### Issue description

1. When you are in the Editor go to the end of the Array in the JSON ( Line 40 )
2. Type a , then new Line and add "test":[{}]
3. Auto format kickes in
4. Cursor is at the bottom after the auto format

### Operating system

- OS: [e.g. iOS]: MacOS
- Browser [e.g. chrome, safari]: Google Chrome

- Testing in Local mode, Docker and Live mode

### Priority this issue should have

Medium (should be fixed soon)

**Comment by Maduki-tech** [comment]
I want to try to Fix it. Any idea where i have to look for the Autoformat?

**Comment by AykutSarac** [comment]
Could you share a short video of the issue?
