### ISSUE TITLE
[BUG]: inbound links no longer working, gets overwritten by default

### ISSUE THREAD

**Issue by AshSimmonds** [AykutSarac/jsoncrack.com#253]
### Issue description

Try using any custom stuff in the JSON window, then export the link, then try and use that link - it always reverts back to the default payload.

### Operating system

- Win11
- Browser: tried Edge, Chrome, Vivaldi

### Priority this issue should have

Medium (should be fixed soon)

**Comment by AykutSarac** [comment]
Can you provide example of data with steps to reproduce?

**Comment by Tatarkow** [comment]
> Can you provide example of data with steps to reproduce?

I'm experiencing the issue as well. For instance, clicking on the following link (obtained by the "Create a Share Link" functionality) results in rendering the default JSON (the one with 3 members).

https://jsoncrack.com/editor?json=%5B%5B%22squadName%22%2C%22a%7C0%22%2C%22Super%20hero%20squad%22%2C%22o%7C1%7C2%22%5D%2C%223%22%5D

**Comment by ahmetilhan24** [comment]
This bug has been fixed by me PR: https://github.com/AykutSarac/jsoncrack.com/pull/278 
fyi @AshSimmonds @Tatarkow

**Comment by AykutSarac** [comment]
Fixed with [v2.5.0](https://github.com/AykutSarac/jsoncrack.com/releases/tag/v2.5.0)
