### ISSUE TITLE
Getting dot notation of JSON on clicking/hovering the edges

### ISSUE THREAD

**Issue by ksksn** [AykutSarac/jsoncrack.com#257]
### Feature

A really good feature would be to get the dot notation on the edges of the graph. Also I should be able to copy the dot notation string. It would be really helpful when working with big nested JSON. 
Here's a screenshot of the feature I am thinking.

![jsoncrackfeature](https://user-images.githubusercontent.com/48342231/201259743-a3394ce2-b1b3-4c1f-8d4a-f7cbd01995d5.jpg)

**Comment by hanbin9775** [comment]
Any one working on this issue? If not, I want to create pr for this feature.

**Comment by AykutSarac** [comment]
> Any one working on this issue? If not, I want to create pr for this feature.

As far as I know nobody working on it currently.
