### ISSUE TITLE
[BUG]: Json query param not working

### ISSUE THREAD

**Issue by aschiavon91** [AykutSarac/jsoncrack.com#260]
### Issue description

make a request with query param `json` containing a stringfied json.
ex: https://jsoncrack.com/editor?json=%7B%22data%22:%22abc%22%7D

### Operating system

- OS: [e.g. iOS]:
  Linux
- Browser [e.g. chrome, safari]:
  Brave
- Any other details...

### Priority this issue should have

Low (slightly annoying)

**Comment by AykutSarac** [comment]
Fixed with [v2.5.0](https://github.com/AykutSarac/jsoncrack.com/releases/tag/v2.5.0)
