### ISSUE TITLE
Edit Json from Graphical interface / Jump to json line

### ISSUE THREAD

**Issue by NielsKorschinsky** [AykutSarac/jsoncrack.com#262]
### Feature

Hi,
I'm having the use case of editing my larger json file with many dictionary and array levels.
It is hard to find a child, using jsoncrack I am now able to find it.

Then, I want to see all the siblings and change one/few attributes of one of them.

To do so, two features would very important for both the VSC integration and the online editor.

1. Using the current pop-up, being able to edit the json dictionary content, e.g. changing a true to false and more.
2. Jump your editing/selected line in the editor to the child you are currently clicking as an alternative option for (larger) changes.

This would also allow me to easily find the correct child in the tree and then jump over to the json file to edit/inspect it.

**Comment by victorbrambati** [comment]
@NielsKorschinsky Good feature and feedback, I will explore it.

**Comment by AykutSarac** [comment]
> @NielsKorschinsky Good feature and feedback, I will explore it.

I'd recommend waiting for version 3 release to start working on it probably, codebase will change significantly :)

**Comment by alete89** [comment]
Editing the JSON from the graph would be the nicest feature!

**Comment by AykutSarac** [comment]
Editing JSON from graph has been added now, other one can be followed up at #192.
