### ISSUE TITLE
Chrome extension when viewing JSON directly

### ISSUE THREAD

**Issue by muuvmuuv** [AykutSarac/jsoncrack.com#263]
### Feature

Like this one here: https://github.com/callumlocke/json-formatter

Guess that would be a great addition to VS Code when viewing large JSON responses in the browser.

**Comment by AykutSarac** [comment]
Would be possible with JSON Crack embed. I'll consider that.

**Comment by bokub** [comment]
Here you go: https://chrome.google.com/webstore/detail/json-crack-formatter/ioanjonjikjnimckmaobngpeheholkko

([Source code](https://github.com/bokub/json-crack-formatter))
