### ISSUE TITLE
[BUG]: Blurred Graph Display

### ISSUE THREAD

**Issue by mickeyl** [AykutSarac/jsoncrack.com#265]
### Issue description

I'm using this here on macOS with Safari and for me, the graph display is always kind of blurry ­– it almost looks as if the zoom works on a bitmap base instead of scaling vectors.

### Operating system

- OS: macOS Ventura 13.0.1
- Browser: macOS Safari
- 

### Priority this issue should have

Low (slightly annoying)

**Comment by mickeyl** [comment]
![Bildschirm­foto 2022-11-24 um 11 59 07](https://user-images.githubusercontent.com/167469/203768075-5170d80f-06f8-414e-8b53-34c1e27a6a55.png)

**Comment by AykutSarac** [comment]
It works fine one my end and haven't received any similar reports yet, I'll look into it but I'd recommend looking for graphical settings on your device.
