### ISSUE TITLE
I have more than 9000 rows of json data, and the visual interface is abnormally stuck and cannot operate normally

### ISSUE THREAD

**Issue by liyang-it** [AykutSarac/jsoncrack.com#271]
### Issue description

I have more than 9000 rows of json data, and the visual interface is abnormally stuck and cannot operate normally

### Operating system

- OS: [e.g. iOS]:
- Browser [e.g. chrome, safari]:

- Any other details...

### Priority this issue should have

Low (slightly annoying)

**Comment by patilbamit** [comment]
Hello @AykutSarac 

Firstly - A excellent tool -JSON CRACK .

The tool hangs up when we load big-size data. This is a frequent USE CASE when we interact with PROD data.
Do we have any solution?  I request to please prioritize accordingly .

**Comment by AykutSarac** [comment]
Unfortunately due to the nature of component libraries there's a limit on how many elements a webpage can render. The premium editor has been rebuilt using Canvas API so if you're working with data regularly I recommend it. For basic usage open-source version is still fine I believe.
