### ISSUE TITLE
User can see trimmed strings if it is too long

### ISSUE THREAD

**Issue by nikolayOrions** [AykutSarac/jsoncrack.com#273]
### Feature

If a JSON field contains long strings the diagram becomes extremely small. 
For instance
![image](https://user-images.githubusercontent.com/91059031/205637900-c5cceba5-9265-45a9-bd25-5c338e4c3e9f.png)
User needs to see trimmed version of a long text
Cut off no more than 50 symbols with ... at the end.
![image](https://user-images.githubusercontent.com/91059031/205638562-2167cc0a-c78e-4fc9-ab7c-fd08d90beeac.png)

**Comment by faizanu94** [comment]
Hey guys, I tried to work on this feature. Here's the PR (https://github.com/AykutSarac/jsoncrack.com/pull/275)

**Comment by AykutSarac** [comment]
Fixed with [v2.5.0](https://github.com/AykutSarac/jsoncrack.com/releases/tag/v2.5.0)
