### ISSUE TITLE
FEATURE REQUEST: Support for modified node contents in Json TREE

### ISSUE THREAD

**Issue by 66Kevin** [AykutSarac/jsoncrack.com#276]
### Feature

Hi.
Thanks for your amazing work！
I have some advice for your feature update. Is it possible to support **modifying** the contents of nodes in the right json tree and can be **updated** to the left json file? It is convenient for modifying contents of nodes under the visualization mode,

Best wishes,
Yueyi Wang

**Comment by ahmetilhan24** [comment]
I tried to add this feature for about 4 hours. But I couldn't do it because there is no backward (to JSON) conversion from NodeData inside. It needs to be developed in the "reaflow" package for it to be done. @66Kevin

**Comment by AykutSarac** [comment]
This has been added now.
