### ISSUE TITLE
[BUG]: Share link opens default JSON

### ISSUE THREAD

**Issue by roboter** [AykutSarac/jsoncrack.com#277]
### Issue description

1. Change JSON
2. Click share
3. copy link
4. open copied link
5. compare with JSON you shared

Expected result you share JSON that you change, not dafault JSON 

### Operating system

- OS: [e.g. iOS]:
- Browser [e.g. chrome, safari]:

- Any other details...

### Priority this issue should have

Medium (should be fixed soon)

**Comment by roboter** [comment]
https://jsoncrack.com/editor?json=%5B%5B%22TOOPAKKUMINE_NUMBER%22%2C%22URL%22%2C%22ASUTUS_NIMI%22%2C%22ASUTUS_REGISTRIKOOD%22%2C%22ASUTUS_BRAND%22%2C%22ASUTUS_KODULEHT%22%2C%22ASUTUS_TUTVUSTUS%22%2C%22ASUTUS_AADRESS%22%2C%22LOGO%22%2C%22TAIENDLOGOD%22%2C%22KONTAKTISIK%22%2C%22KONTAKTISIK_AMET%22%2C%22TELEFON%22%2C%22EMAIL%22%2C%22NIMETUS%22%2C%22AMETINIMETUS_TAPSUSTUS%22%2C%22GRUPP_KOOD%22%2C%22GRUPP_NIMETUS%22%2C%22VANEM_GRUPP_KOOD%22%2C%22VANEM_GRUPP_NIMETUS%22%2C%22KOHTADE_ARV%22%2C%22KANDIDEERIMISE_KP%22%2C%22TOOLEASUMINE%22%2C%22ON_AVALIK_TEENISTUS%22%2C%22ON_TAISKOHAGA%22%2C%22ON_OSAKOHAGA%22%2C%22KOORMUS_TAPSUSTUS%22%2C%22ON_VAHETUSTEGA%22%2C%22ON_OOSITI%22%2C%22TOOAEG_TAPSUSTUS%22%2C%22TOOTASU_ALATES%22%2C%22TOOTASU_KUNI%22%2C%22TOOTASU_TAPSUSTUS%22%2C%22TOOSUHTE_KESTUS%22%2C%22TAHTAJA_TAPSUSTUS%22%2C%22TOO_ASUKOHA_AADRESSID%22%2C%22ON_KODUS_TOOTAMINE%22%2C%22TOOYLESANDED%22%2C%22OMALT_POOLT_PAKUME%22%2C%22HARIDUS_TASE%22%2C%22HARIDUS_VALDKONNAD%22%2C%22VARASEM_TOOKOGEMUS%22%2C%22AMETITUNNISTUSED%22%2C%22KUTSETUNNISTUSED%22%2C%22KEELEOSKUS%22%2C%22ON_NOUTUD_YKS_KEEL%22%2C%22JUHILUBA%22%2C%22ARVUTIOSKUS%22%2C%22ARVUTIOSKUS_TAPSUSTUS%22%2C%22NOUDED%22%2C%22LISAINFO%22%2C%22KANDIDEERIMISE_DOKUMENDID%22%2C%22LINK_KANDIDEERIMISE_KESKKONDA%22%2C%22a%7C0%7C1%7C2%7C3%7C4%7C5%7C6%7C7%7C8%7C9%7CA%7CB%7CC%7CD%7CE%7CF%7CG%7CH%7CI%7CJ%7CK%7CL%7CM%7CN%7CO%7CP%7CQ%7CR%7CS%7CT%7CU%7CV%7CW%7CX%7CY%7CZ%7Ca%7Cb%7Cc%7Cd%7Ce%7Cf%7Cg%7Ch%7Ci%7Cj%7Ck%7Cl%7Cm%7Cn%7Co%7Cp%7Cq%22%2C%22686523%22%2C%22https%3A%2F%2Fwww.tootukassa.ee%2Ftoopakkumised%2Fgrillmeister-autojuht-686523%22%2C%22Marmerol%20O%C3%9C%22%2C%2214486118%22%2C%22RIIK_ISO_KOOD%22%2C%22RIIK_NIMI%22%2C%22ADRID%22%2C%22ADOBID%22%2C%22TEKST%22%2C%22POSTIINDEKS%22%2C%22a%7Cw%7Cx%7Cy%7Cz%7C10%7Co%7C11%22%2C%22EE%22%2C%22Eesti%22%2C%222592234%22%2C%227712079%22%2C%22Ida-Viru%20maakond%2C%20Toila%20vald%2C%20Toila%20alevik%2C%20Mere%20pst%204%22%2C%2241702%22%2C%22o%7C12%7C13%7C14%7C15%7C16%7C17%7C%7C18%22%2C%22a%7C%22%2C%22Aivar%20Tamm%22%2C%22Juhatuse%20liige%22%2C%2253014414%22%2C%22grillkanaauto%40gmail.com%22%2C%22Grillmeister-autojuht%22%2C%22Grillkana%20m%C3%BC%C3%BCja%20-%20autojuht%22%2C%2255%22%2C%22toitlustus%2C%20majutus%2C%20%C3%BCrituste%20korraldus%22%2C%2220%22%2C%22Turism%2C%20hotellindus%22%2C%22n%7C1%22%2C%2231.12.2022%22%2C%22ON_KIIRESTI_VAJA%22%2C%22AASTA%22%2C%22KUU%22%2C%22PAEV%22%2C%22a%7C1N%7C1O%7C1P%7C1Q%22%2C%22o%7C1R%7C1L%7C%7C%7C%22%2C%22n%7C0%22%2C%22Iga%20p%C3%A4ev%20vastavalt%20kokkuleppele.%22%2C%22t%C3%A4htajatu%22%2C%222591917%22%2C%228007700%22%2C%22Ida-Viru%20maakond%2C%20Toila%20vald%2C%20Toila%20alevik%22%2C%22o%7C12%7C13%7C14%7C1W%7C1X%7C1Y%7C%7C18%22%2C%22a%7C1Z%22%2C%22Grillkana%20autoga%20s%C3%B5itmine%20objektile%3B%20grillkana%2C%20seakoodi%20ja%20teiste%20toodete%20valmistamine%20ning%20m%C3%BC%C3%BCmine.%20%22%2C%22Head%20ja%20tugevat%20meeskonda.%20V%C3%A4lja%C3%B5pet%20kohapeal.%22%2C%22KEEL%22%2C%22KONE_TASE%22%2C%22KIRJA_TASE%22%2C%22ON_NOUTUD%22%2C%22a%7C1d%7C1e%7C1f%7C1g%22%2C%22ET%22%2C%22B2%22%2C%22A2%22%2C%22o%7C1h%7C1i%7C1j%7C1k%7C1T%22%2C%22a%7C1l%22%2C%22KATEGOORIA%22%2C%22a%7C1n%22%2C%22B%22%2C%22o%7C1o%7C1p%22%2C%22a%7C1q%22%2C%22o%7Cr%7Cs%7Ct%7Cu%7Cv%7C%7C%7C%7C19%7C%7C1A%7C1B%7C1C%7C1D%7C1E%7C1F%7C1G%7C1H%7C1I%7C1J%7C1K%7C1L%7C1M%7C1S%7C1T%7C1L%7C1T%7C%7C1T%7C1T%7C1U%7C%7C%7C%7C1V%7C%7C1a%7C1T%7C1b%7C1c%7C%7C1A%7C%7C1A%7C1A%7C1m%7C1T%7C1r%7C%7C%7C%7C%7C1A%7C%22%5D%2C%221s%22%5D

**Comment by roboter** [comment]
full JSON:
{
  "TOOPAKKUMINE_NUMBER": "686523",
  "URL": "https://www.tootukassa.ee/toopakkumised/grillmeister-autojuht-686523",
  "ASUTUS_NIMI": "Marmerol OÜ",
  "ASUTUS_REGISTRIKOOD": "14486118",
  "ASUTUS_BRAND": null,
  "ASUTUS_KODULEHT": null,
  "ASUTUS_TUTVUSTUS": null,
  "ASUTUS_AADRESS": {
    "RIIK_ISO_KOOD": "EE",
    "RIIK_NIMI": "Eesti",
    "ADRID": "2592234",
    "ADOBID": "7712079",
    "TEKST": "Ida-Viru maakond, Toila vald, Toila alevik, Mere pst 4",
    "LISAINFO": null,
    "POSTIINDEKS": "41702"
  },
  "LOGO": null,
  "TAIENDLOGOD": [],
  "KONTAKTISIK": "Aivar Tamm",
  "KONTAKTISIK_AMET": "Juhatuse liige",
  "TELEFON": "53014414",
  "EMAIL": "grillkanaauto@gmail.com",
  "NIMETUS": "Grillmeister-autojuht",
  "AMETINIMETUS_TAPSUSTUS": "Grillkana müüja - autojuht",
  "GRUPP_KOOD": "55",
  "GRUPP_NIMETUS": "toitlustus, majutus, ürituste korraldus",
  "VANEM_GRUPP_KOOD": "20",
  "VANEM_GRUPP_NIMETUS": "Turism, hotellindus",
  "KOHTADE_ARV": 1,
  "KANDIDEERIMISE_KP": "31.12.2022",
  "TOOLEASUMINE": {
    "ON_KIIRESTI_VAJA": 1,
    "AASTA": null,
    "KUU": null,
    "PAEV": null
  },
  "ON_AVALIK_TEENISTUS": 0,
  "ON_TAISKOHAGA": 1,
  "ON_OSAKOHAGA": 0,
  "KOORMUS_TAPSUSTUS": null,
  "ON_VAHETUSTEGA": 0,
  "ON_OOSITI": 0,
  "TOOAEG_TAPSUSTUS": "Iga päev vastavalt kokkuleppele.",
  "TOOTASU_ALATES": null,
  "TOOTASU_KUNI": null,
  "TOOTASU_TAPSUSTUS": null,
  "TOOSUHTE_KESTUS": "tähtajatu",
  "TAHTAJA_TAPSUSTUS": null,
  "TOO_ASUKOHA_AADRESSID": [
    {
      "RIIK_ISO_KOOD": "EE",
      "RIIK_NIMI": "Eesti",
      "ADRID": "2591917",
      "ADOBID": "8007700",
      "TEKST": "Ida-Viru maakond, Toila vald, Toila alevik",
      "LISAINFO": null,
      "POSTIINDEKS": "41702"
    }
  ],
  "ON_KODUS_TOOTAMINE": 0,
  "TOOYLESANDED": "Grillkana autoga sõitmine objektile; grillkana, seakoodi ja teiste toodete valmistamine ning müümine. ",
  "OMALT_POOLT_PAKUME": "Head ja tugevat meeskonda. Väljaõpet kohapeal.",
  "HARIDUS_TASE": null,
  "HARIDUS_VALDKONNAD": [],
  "VARASEM_TOOKOGEMUS": null,
  "AMETITUNNISTUSED": [],
  "KUTSETUNNISTUSED": [],
  "KEELEOSKUS": [
    {
      "KEEL": "ET",
      "KONE_TASE": "B2",
      "KIRJA_TASE": "A2",
      "ON_NOUTUD": 0
    }
  ],
  "ON_NOUTUD_YKS_KEEL": 0,
  "JUHILUBA": [
    {
      "KATEGOORIA": "B"
    }
  ],
  "ARVUTIOSKUS": null,
  "ARVUTIOSKUS_TAPSUSTUS": null,
  "NOUDED": null,
  "LISAINFO": null,
  "KANDIDEERIMISE_DOKUMENDID": [],
  "LINK_KANDIDEERIMISE_KESKKONDA": null
}

**Comment by sanmins** [comment]
လိမ်းညာဎွ

တနင်္လာနေ့၊ ဒီဇင်ဘာ 12 ရက်၊ 2022 တွင် Aleksei Prokopov <
***@***.***> မှရေးသားခဲ့သည်

**Comment by eduwass** [comment]
I'm experiencing this too. 

Example: 

`
https://jsoncrack.com/editor?json=%5B%5B%22settings%22%2C%22styles%22%2C%22version%22%2C%22%24schema%22%2C%22a%7C0%7C1%7C2%7C3%22%2C%22color%22%2C%22layout%22%2C%22spacing%22%2C%22typography%22%2C%22a%7C5%7C6%7C7%7C8%22%2C%22palette%22%2C%22a%7CA%22%2C%22name%22%2C%22slug%22%2C%22a%7C5%7CC%7CD%22%2C%22%23103059%22%2C%22Primary%22%2C%22primary%22%2C%22o%7CE%7CF%7CG%7CH%22%2C%22%2396C2E5%22%2C%22Secondary%22%2C%22secondary%22%2C%22o%7CE%7CJ%7CK%7CL%22%2C%22a%7CI%7CM%22%2C%22o%7CB%7CN%22%2C%22contentSize%22%2C%22wideSize%22%2C%22a%7CP%7CQ%22%2C%221100px%22%2C%221980px%22%2C%22o%7CR%7CS%7CT%22%2C%22margin%22%2C%22padding%22%2C%22units%22%2C%22a%7CV%7CW%7CX%22%2C%22b%7CT%22%2C%22px%22%2C%22em%22%2C%22rem%22%2C%22vh%22%2C%22vw%22%2C%22%25%22%2C%22a%7Ca%7Cb%7Cc%7Cd%7Ce%7Cf%22%2C%22o%7CY%7CZ%7CZ%7Cg%22%2C%22fontFamilies%22%2C%22fontSizes%22%2C%22a%7Ci%7Cj%22%2C%22fontFamily%22%2C%22a%7Cl%7CC%7CD%22%2C%22%5C%22Poppins%5C%22%2C%20sans-serif%22%2C%22Poppins%22%2C%22o%7Cm%7Cn%7Co%7CH%22%2C%22a%7Cp%22%2C%22size%22%2C%22a%7CC%7Cr%7CD%22%2C%22Extra%20small%22%2C%221rem%22%2C%22extra-small%22%2C%22o%7Cs%7Ct%7Cu%7Cv%22%2C%22Small%22%2C%221.125rem%22%2C%22small%22%2C%22o%7Cs%7Cx%7Cy%7Cz%22%2C%22Medium%22%2C%221.25rem%22%2C%22medium%22%2C%22o%7Cs%7C11%7C12%7C13%22%2C%22Large%22%2C%222rem%22%2C%22large%22%2C%22o%7Cs%7C15%7C16%7C17%22%2C%22XL%22%2C%222.75rem%22%2C%22x-large%22%2C%22o%7Cs%7C19%7C1A%7C1B%22%2C%22XXL%22%2C%223.75rem%22%2C%22xx-large%22%2C%22o%7Cs%7C1D%7C1E%7C1F%22%2C%22a%7Cw%7C10%7C14%7C18%7C1C%7C1G%22%2C%22o%7Ck%7Cq%7C1H%22%2C%22o%7C9%7CO%7CU%7Ch%7C1I%22%2C%22elements%22%2C%22a%7C5%7C1K%7C7%7C8%22%2C%22text%22%2C%22a%7C1M%22%2C%22var%3Apreset%7Ccolor%7Cprimary%22%2C%22o%7C1N%7C1O%22%2C%22button%22%2C%22heading%22%2C%22link%22%2C%22a%7C1Q%7C1R%7C1S%22%2C%22a%7C8%22%2C%22a%7Cl%22%2C%22o%7C1V%7Cn%22%2C%22o%7C1U%7C1W%22%2C%22o%7C1T%7C1X%7C1X%7C1X%22%2C%22a%7CW%22%2C%22bottom%22%2C%22left%22%2C%22right%22%2C%22top%22%2C%22a%7C1a%7C1b%7C1c%7C1d%22%2C%220px%22%2C%22o%7C1e%7C1f%7C1f%7C1f%7C1f%22%2C%22o%7C1Z%7C1g%22%2C%22var%3Apreset%7Cfont-family%7Cprimary%22%2C%22o%7C1V%7C1i%22%2C%22o%7C1L%7C1P%7C1Y%7C1h%7C1j%22%2C%22n%7C2%22%2C%22https%3A%2F%2Fschemas.wp.org%2Fwp%2F6.1%2Ftheme.json%22%2C%22o%7C4%7C1J%7C1k%7C1l%7C1m%22%5D%2C%221n%22%5D
`

**Comment by AykutSarac** [comment]
Fixed with https://github.com/AykutSarac/jsoncrack.com/releases/tag/v2.5.0

**Comment by cryoff** [comment]
Is this bug present again? Or maybe i'm doing something wrong

**Comment by AykutSarac** [comment]
> Is this bug present again? Or maybe i'm doing something wrong

Old links are no longer supported.
