### ISSUE TITLE
[BUG]: File upload button looks like it accepts drag and drop but it doesn't.

### ISSUE THREAD

**Issue by Secret-chest** [AykutSarac/jsoncrack.com#283]
### Issue description

1. click "import file" in the sidebar
2. try dropping a file on the box that appears
3. it's just a very big and deceptively styled button

### Operating system

- OS: [e.g. iOS]: Linux Mint 21
- Browser [e.g. chrome, safari]: chromium 208

- Any other details...

### Priority this issue should have

Low (slightly annoying)

**Comment by AykutSarac** [comment]
You're right, it supposed to accept drag & import. I'm replacing the label with feature and adding confirmed if anyone wants to implement it.

**Comment by liqun98** [comment]
Hey guys, I tried to work on this feature. Here's the PR (#284)
