### ISSUE TITLE
Disable Google Login in docker-compose

### ISSUE THREAD

**Issue by janmarcopetri** [AykutSarac/jsoncrack.com#287]
### Feature

Is it possible to set an environment variable in docker-compose to disable the Google login feature in the newer versions of jsoncrack? Couldn't find anything regarding this...

### Alternative solutions or implementations

Add an environment variable for docker-compose to disable Google login.
Because of privacy reasons and the data protection laws in some countries it might be very useful to disable the (Google) login option, depending on the use case of the self-hosted docker instance of jsoncrack.

**Comment by AykutSarac** [comment]
Specific environment should be added to prevent endpoint actions and set default placeholder user.

**Comment by janmarcopetri** [comment]
Hi, any update on this? We would very much appreciate if it was possible to disable the register and sign-in -features.

**Comment by AykutSarac** [comment]
> Hi, any update on this? We would very much appreciate if it was possible to disable the register and sign-in -features.

You should be signed-in to placeholder account by default on localhost.
