### ISSUE TITLE
[BUG]: Root node resolution is incorrect

### ISSUE THREAD

**Issue by Jesn** [AykutSarac/jsoncrack.com#288]
### Issue description

Root node resolution is incorrect
![image](https://user-images.githubusercontent.com/5728274/210681885-5dfbb225-54cb-43df-8092-6d33b6cd0802.png)

### Operating system

- OS: [e.g. iOS]:
- Browser [e.g. chrome, safari]:

- Any other details...

### Priority this issue should have

Low (slightly annoying)

**Comment by AykutSarac** [comment]
It's corret. The outgoing nodes means that they're part of the root but has childs (it's either an array or object).
