### ISSUE TITLE
[BUG]: Default example when landing on the /editor is inconsistent

### ISSUE THREAD

**Issue by RDalcolmo** [AykutSarac/jsoncrack.com#290]
### Issue description

The default example which shows how a JSON file is visualized shows an inconsistency. When you look at the root object you can see the strings are represented as "myStringValue"

![image](https://user-images.githubusercontent.com/9065913/210864884-e5078eaf-60a2-4887-a6d3-2707a95f0523.png)

But when you go to the very end of the json tree, you can see an array of strings does not have the quotes on them and are colored green

![image](https://user-images.githubusercontent.com/9065913/210864969-a85805ac-56e2-4880-a4de-07c0615d40cf.png)

My suggestion is to make them consistent and turn the green string representation into the regular white with quotes

### Operating system

- OS: [e.g. iOS]: Windows 10
- Browser [e.g. chrome, safari]: Chrome

### Priority this issue should have

Low (slightly annoying)

**Comment by AykutSarac** [comment]
Hello, that's the intended behaviour.  I'd love to hear what other thinks here and appropriate actions could be considered upon feedbacks.

**Comment by RDalcolmo** [comment]
I would love to see colors being consistent with the type strings = white, booleans = green, numbers = yellow
