### ISSUE TITLE
Hope to be compatible with macOS touchpad events !

### ISSUE THREAD

**Issue by TaroXin** [AykutSarac/jsoncrack.com#298]
### Feature

I often use MacBook Pro to browse the web and perform some operations. When I use the software, I noticed that on the Crack page, it cannot respond well to touchpad events. For example, two-finger scrolling is now a zoom effect, nor can Responsive pinch-to-zoom

So I hope that this judgment can be added to be compatible with the related operations of the macOS touchpad

Thank you very much for your open source

**Comment by AykutSarac** [comment]
Hello, I use MacBook Pro as well and it performs well on touchpad. Are there any specific touchpad events can be improved?

**Comment by TaroXin** [comment]
@AykutSarac Hi, I hope that I can use the touchpad to move the legend with two fingers, but using two fingers is the effect of zooming the legend. I think it is possible to refer to the form of Xmind

My two-finger scrolling in action

![move](https://user-images.githubusercontent.com/19855713/211491378-f11643f7-a751-4e5b-a7ad-b4ceea13ef4b.gif)

**Comment by AykutSarac** [comment]
Should be working now.
