### ISSUE TITLE
[BUG]: I simply cannot get it to display graph on VSCode

### ISSUE THREAD

**Issue by ctrebbau** [AykutSarac/jsoncrack.com#300]
### Issue description

I've tried disabling/enabling extension, uninstalling/installing extension, uninstalling/installing vscode to no effect. JSON Language Server.log is empty.  
![Screenshot 2023-01-19 at 10 05 18](https://user-images.githubusercontent.com/84703650/213401085-951ca420-8c52-4764-8130-16e466d4e989.png)

### Operating system

Platform Info:
  OS: macOS (x86_64-apple-darwin21.4.0)
  CPU: 12 × Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  WORD_SIZE: 64

### Priority this issue should have

Medium (should be fixed soon)

**Comment by Mohamed3nan** [comment]
Same here

**Comment by AykutSarac** [comment]
This will be handled at [JSON Crack's VS Code repository](https://github.com/AykutSarac/jsoncrack-vscode).
