### ISSUE TITLE
[BUG]: Embed height is too high

### ISSUE THREAD

**Issue by bokub** [AykutSarac/jsoncrack.com#301]
### Issue description

Hello,
It looks like you added a toolbar in embeds.

That's a good idea, but now all embeds have a scrollbar, because of it.

Example in [your own CodePen](https://codepen.io/AykutSarac/pen/QWBbpqx)

### Media & Screenshots

![image](https://user-images.githubusercontent.com/17952318/214374810-5f386ec7-03c4-4d51-932c-a37142af120b.png)

### Operating system

- OS: Ubuntu
- Browser: chrome

### Priority this issue should have

Low (slightly annoying)

**Comment by AykutSarac** [comment]
Fixed with latest commit
