### ISSUE TITLE
[BUG]: <TypeError: Cannot read properties of undefined (reading 'config')>

### ISSUE THREAD

**Issue by mysunset** [AykutSarac/jsoncrack.com#314]
### Issue description

TypeError: Cannot read properties of undefined (reading 'config')

The error comes from this file:"src\components\MonacoEditor\index.tsx"
   7 | import styled from "styled-components";
   8 | 
   9 | loader.config({
  10 | paths: {
  ->11 |   vs: "https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.34.0/min/vs",
  12 | },

This url, "https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.34.0/min/vs", is empty

![1](https://user-images.githubusercontent.com/28687305/222416872-ef028473-cac3-4c4a-acbc-2da5912dd1c8.png)

### Operating system

- OS: [Windows 10]:
- Browser [chrome 110.0.5481.178]:

### Priority this issue should have

Low (slightly annoying)

**Comment by AykutSarac** [comment]
Hello,

The URL you mentioned is actually a directory fetches the editor from here https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.34.0/min/vs/editor/editor.main.js I've tested and didn't encounter any problems.

**Comment by mysunset** [comment]
Thank you very much!The error is really not due to this url.
