### ISSUE TITLE
Extension for Jetbrains

### ISSUE THREAD

**Issue by re3factor** [AykutSarac/jsoncrack.com#323]
### Feature

Not a VS Code user so I figured I would just ask if you could make an extension for JetBrains IDEs

**Comment by i-am-unknown-81514525** [comment]
Agreed, it would be extremely helpful

**Comment by wuguangping** [comment]
+1

**Comment by AntonShuvaev** [comment]
Take a look at this plugin https://plugins.jetbrains.com/plugin/22472-datagraph--json-yaml-xml-visualization

**Comment by i-am-unknown-81514525** [comment]
It require £1.5/year which not very helpful as it requires me to pay to use it

**Comment by mamachnik** [comment]
duplicate of #269 but still it would be nice too see a JetBrains plugin.

**Comment by mamachnik** [comment]
https://github.com/AykutSarac/jsoncrack.com/issues/344#issue-1811866371 seems to be a promising solution @wuguangping @i-am-unknown-81514525 @re3factor

**Comment by AykutSarac** [comment]
Closing as duplicate of #269
