### ISSUE TITLE
[BUG]: <Context of the issue>docker

### ISSUE THREAD

**Issue by Frenz86** [AykutSarac/jsoncrack.com#324]
### Issue description

docker build doesn't work
ERROR [builder 4/4] RUN yarn install --frozen-lockfile && yarn build

### Operating system

- OS: [e.g. iOS]:
- Browser [e.g. chrome, safari]:

- Any other details...

### Priority this issue should have

Low (slightly annoying)

**Comment by dont-know-php** [comment]
hi @Frenz86 , just change the node version in the Dockerfile from 14 to 16:

```Dockerfile
FROM node:16-alpine as builder
```

**Comment by JinnaBalu** [comment]
Latest base image `FROM node:18-alpine as builder` is working fine.
