### ISSUE TITLE
[BUG]: Weird order of display

### ISSUE THREAD

**Issue by Temepest74** [AykutSarac/jsoncrack.com#325]
### Issue description

Add this json:
```
[
  {
    "id": 1,
    "value": 21
  },
  {
    "id": 2,
    "value": 40
  },
  {
    "id": 3,
    "value": 12
  },
  {
    "id": 4,
    "value": 1
  }
]
```
I expect it to be displayed in this order, or at least to be displayed in the order of ids, but it is displayed like ![image](https://user-images.githubusercontent.com/28103890/229050492-be18639a-0497-437a-b5ae-376764d8f095.png)

### Operating system

- OS: win11
- Browser: Mozilla

### Priority this issue should have

Low (slightly annoying)

**Comment by NitinRamnani** [comment]
It's the issue with reaflow (one of the dependencies of the project).

https://github.com/reaviz/reaflow/issues/92
