### ISSUE TITLE
[BUG]: Problems when run docker build in some tags

### ISSUE THREAD

**Issue by vitormds22** [AykutSarac/jsoncrack.com#330]
### Issue description

When i try to run the command `docker build -t jsoncrack .` i receive an error on my terminal:

```shell
ReferenceError: AbortController is not defined
    at fetchCSSFromGoogleFonts (/src/node_modules/next/dist/compiled/@next/font/dist/google/fetch-css-from-google-fonts.js:34:28)
    at nextFontGoogleFontLoader (/src/node_modules/next/dist/compiled/@next/font/dist/google/loader.js:76:79)
    at /src/node_modules/next/dist/build/webpack/loaders/next-font-loader/index.js:72:99
    at async Span.traceAsyncFn (/src/node_modules/next/dist/trace/trace.js:79:20)
Failed to compile.

src/components/CustomNode/styles.tsx
`next/font` error:
Failed to fetch `Roboto Mono` from Google Fonts.

src/components/CustomNode/styles.tsx
An error occured in `next/font`.

NextFontError: Failed to fetch `Roboto Mono` from Google Fonts.
{...}
```

This happens when I clone the repository from the main or when I download the v2.8.0 available tag

Someone was pass through this ?

### Operating system

- OS: Ubuntu LTS 24.04
- Browser [e.g. chrome, safari]: Brave
- Terminal: Tilix with zsh

### Priority this issue should have

Low (slightly annoying)

**Comment by adamnock** [comment]
This is a node version compatibility issue. Upgrading the node version (currently Dockerfile specifies 14) to 15+ resolves

Tested just now using node:latest, no issues with build

**Comment by vitormds22** [comment]
Thanks @adamnock , this is work for me. 

For curiosity, how did you know ?

**Comment by adamnock** [comment]
@vitormds22 bit of googling about specifically "Failed to fetch `Roboto Mono` from Google Fonts." and found the answer in this thread https://github.com/vercel/next.js/issues/45080
