### ISSUE TITLE
[BUG]: <jsoneditor does not update after getting data from query.url>

### ISSUE THREAD

**Issue by derlans** [AykutSarac/jsoncrack.com#332]
### Issue description

When I try to bring a query url to the link, I find that the image will be updated but the content of jsoneditor will not be updated.
[For example ](https://jsoncrack.com/editor?url=https%3A%2F%2Fproapi.azurewebsites.net%2Fdoc%2FgetAvatarList%3Ffilename%3Dcomponents%2Flist%2Findex.zh-CN.md%26owner%3Dant-design%26repo%3Dant-design)
![演示](https://github.com/AykutSarac/jsoncrack.com/assets/58926947/0a22ebc2-1c6c-4019-ba38-71cc2605bbdb)

### Operating system

- OS: [e.g. iOS]:
- Browser [e.g. chrome, safari]:

- Any other details...

### Priority this issue should have

Low (slightly annoying)

**Comment by AykutSarac** [comment]
Thanks for the report, should be fixed now.
