### ISSUE TITLE
[BUG]:  Sorting in Nested Array

### ISSUE THREAD

**Issue by showenx** [AykutSarac/jsoncrack.com#334]
### Issue description

In VS Code 1.78.2

I was trying following json with the extesion, the sorting is a bit off.

Expecting the sorting sequence for nested array is aligned with original data sequence.

```json
[
    [
        {
            "name": "1111"
        },
        {
            "name": "2222"
        }
    ],
    [
        {
            "name": "3333"
        },
        {
            "name": "4444"
        }
    ],
    [
        {
            "name": "5555"
        },
        {
            "name": "66666"
        }
    ],
    [
        {
            "name": "7777"
        },
        {
            "name": "88888"
        }
        
    ]
]
```

![arr](https://github.com/AykutSarac/jsoncrack.com/assets/3623139/50a48f8d-e962-4b85-baee-7c894d98f2c9)

### Priority this issue should have

Medium (should be fixed soon)

**Comment by AykutSarac** [comment]
It was confirmed that, this is a problem with [reaflow](https://github.com/reaviz/reaflow).
