### ISSUE TITLE
[BUG]: changing values on viewer

### ISSUE THREAD

**Issue by elisonrj** [AykutSarac/jsoncrack.com#339]
### Issue description

Json:
{"contador": {"numSerie": 101000001716225757, "propriedade": 0, "dataInstalacao": "2021-12-23 00:00:00+0000", "dataLevantamento": "9999-12-31 00:00:00+0000"}}

Screenshot:
![2023-06-24_json_crack](https://github.com/AykutSarac/jsoncrack.com/assets/34030988/1fffe9ac-1d24-453b-8cd3-9e81274f8da1)

### Operating system

- OS: Windows 11
- Browser: Chrome Version 114.0.5735.134 (Official Build) (64-bit)

### Priority this issue should have

Low (slightly annoying)

**Comment by AykutSarac** [comment]
It's likely because it exceeds [MAX_SAFE_INTEGER (9007199254740991)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER).
