### ISSUE TITLE
[BUG]: Node padding doesn't work on Firefox

### ISSUE THREAD

**Issue by Eldemarkki** [AykutSarac/jsoncrack.com#346]
### Issue description

On Firefox:
![image](https://github.com/AykutSarac/jsoncrack.com/assets/38920928/eaef2e16-8f28-4a3e-9f3c-90f73cb64ddc)

On Chrome:
![image](https://github.com/AykutSarac/jsoncrack.com/assets/38920928/dd098bfe-fbac-46e9-b48c-f6de1b4cbeb4)

Here's the input I used:

```json
{
  "foo": 123,
  "bar": 123,
  "baz": 123
}
```

This problem seems to only appear on object nodes (not sure if that's what they are called), not on array name nodes or array string value nodes:

![image](https://github.com/AykutSarac/jsoncrack.com/assets/38920928/d53df210-bfb7-47e3-aa90-2b1f11a1f86f)

I investigated this a bit, and it seems to be caused by some problems with `padding` on a `<foreignObject>`, that may be a good place to start looking further.

### Operating system

EndeavourOS (Arch Linux), Firefox version 115.0.3 (64-bit)
![image](https://github.com/AykutSarac/jsoncrack.com/assets/38920928/2cc5a476-63c7-452f-9c4e-59b2c573c1b9)

### Priority this issue should have

Low (slightly annoying)

**Comment by AykutSarac** [comment]
This has been fixed.
