### ISSUE TITLE
Docker-compose file 

### ISSUE THREAD

**Issue by UncleWeeds** [AykutSarac/jsoncrack.com#355]
### Feature

I mean why to use two separate commands when we can just create a docker-compose file and use a single command "docker-compose up" to run the application locally

**Comment by giripriyadarshan** [comment]
is this what you meant? [docker-compose.yml](https://github.com/AykutSarac/jsoncrack.com/blob/a998d849f72611282a9ba15f5c2bffc7836d2f3c/docker-compose.yml)
