### ISSUE TITLE
Add a timer before refreshing the diagram

### ISSUE THREAD

**Issue by zbalkan** [AykutSarac/jsoncrack.com#357]
### Feature

When one needs to update the JSON data to fix the structural or syntactical issues, it is frustrating to refresh on every action.

### Alternative solutions or implementations

It may be possible to use a timer which would be reset on each change action. Therefore, if I start typing or removing within the "sliding window" of a 800-1000ms-timer, it can be reset to count down. Then, if the timer hits 0, it can then redraw the diagram, or refresh partially depending on the internals.

**Comment by AykutSarac** [comment]
It currently doesn't update on every action actually, there's 200ms debounce. Though, you may prefer to manually transform the data into graph. It's at the bottom bar.
<img width="208" alt="image" src="https://github.com/AykutSarac/jsoncrack.com/assets/47941171/aefd85c6-fbe4-4f8f-986d-89861a54ac2c">

**Comment by zbalkan** [comment]
Then, it's my bad. It's probably too short for me. I also didn't know the ability to disable the feature.

Closing the comment as already fixed.
