### ISSUE TITLE
[BUG]: It doesn't run locally

### ISSUE THREAD

**Issue by TheEmperor27** [AykutSarac/jsoncrack.com#372]
### Issue description

after installation and going to http://localhost:3000/
it shows this error:
![2023-12-25 13_32_00-Mozilla Firefox](https://github.com/AykutSarac/jsoncrack.com/assets/61402095/705eaeaf-fbc3-48f3-81db-f70f18325304)

### Operating system

- OS: [e.g. iOS]: Windows 10 Pro
- Browser [e.g. chrome, safari]: Firefox Browser 121.0 (64-bit)

- Any other details...

Next.js 14.0.4
   - Local:        http://localhost:3000
   - Environments: .env.development

node js: V20.10.0
pnpm: 8.12.1

### Priority this issue should have

Medium (should be fixed soon)

**Comment by AykutSarac** [comment]
Can you try deleting `.node_modules` and doing `pnpm install`?

**Comment by TheEmperor27** [comment]
done.
the pnpm install command shows no error and the problem persists

**Comment by khnbzkrt** [comment]
> done. the pnpm install command shows no error and the problem persists

What is your node version?

My versions :
node : 20.9.0
pnpm version : 8.13.1

It's working for me.

**Comment by TheEmperor27** [comment]
I updated to: pnpm:8.13.1
node: 20.10.0

**Comment by AykutSarac** [comment]
Is this fixed?
