### ISSUE TITLE
[BUG]: <Context of the issue>

### ISSUE THREAD

**Issue by lujiashuai-linyin** [AykutSarac/jsoncrack.com#379]
### Issue description

It seems that focusing on operations is ineffective in tree display mode, and the current tree pattern seems to be unable to expand all nodes at once.

https://github.com/AykutSarac/jsoncrack.com/assets/90499546/39ae7e27-3e66-4d1d-9be9-bc6aab9d4ee0

### Operating system

- OS: [e.g. iOS]:
- Browser [e.g. chrome, safari]:

- Any other details...

### Priority this issue should have

Medium (should be fixed soon)

**Comment by AykutSarac** [comment]
Unsupported actions are now hidden within the View menu.
