### ISSUE TITLE
Do we still have the limitation of json size if we deploy a local version on my own machine?

### ISSUE THREAD

**Issue by sudoghut** [AykutSarac/jsoncrack.com#382]
### Feature

Is it possible to remove the json size limitation for local users? When I try to visualize a big json (14333 lines) in my local version (deployed the open-sourced version in my local environment) of jsoncrack. Jsoncrack shows that I still need to subscribe to the pro version. Is that a feature that you expected, or is there a freedom for local open-sourced users to visualize a big json without limitation? Thanks.

![image](https://github.com/AykutSarac/jsoncrack.com/assets/8538710/c163ff6f-0cb1-4327-925f-2c784e2409e0)

**Comment by AykutSarac** [comment]
Limitations are not disabled by default but you can tweak it within `useUser.ts`.

**Comment by AntoineLu** [comment]
How to do so? I do not find this file in the source.
Best.

**Comment by sudoghut** [comment]
> How to do so? I do not find this file in the source. Best.

Now, the solution is to add a line comment to `return <NotSupported />;` in `jsoncrack.com\src\containers\Editor\components\views\GraphView\index.tsx`.

https://github.com/AykutSarac/jsoncrack.com/blob/59c2588709e3ee3c560493616fcebdfbe683a0c7/src/containers/Editor/components/views/GraphView/index.tsx#L169
