### ISSUE TITLE
[BUG]: View mode toggle

### ISSUE THREAD

**Issue by Sabin-Adhikari** [AykutSarac/jsoncrack.com#384]
### Issue description

Feature

Hi guys,
I was not able to find a documentation on the view mode while using embed API
I have the following js script:

```javascript
        let iframe = document.createElement('iframe')
        iframe.id = 'json-crack-iframe'
        iframe.style.border = 'none'
        iframe.height = '1000px'
        iframe.width = '100%'
        iframe.src = "https://jsoncrack.com/widget"
        getShadowRootElementByID('json-crack-container')?.appendChild(iframe)
        const json = JSON.stringify(this.ratingResPayload)
        const options = {
          theme: "light", // "light" or "dark"
          direction: "RIGHT", // "UP", "DOWN", "LEFT", "RIGHT"
        }
window?.addEventListener("message", (event) => {
            iframe.contentWindow?.postMessage({json,options}, "*");
        })
```

I would like to toggle between graph mode and tree mode like in the website.
Is there an option that I can pass?
Thanks in advance!

### Operating system

- OS: [e.g. iOS]:
- Browser [e.g. chrome, safari]:

- Any other details...

### Priority this issue should have

Medium (slightly annoying)

**Comment by AykutSarac** [comment]
This currently not supported but if anyone is down to open a PR I can review.

**Comment by Julias0** [comment]
Can someone assign this to me - I can take a stab at this

**Comment by AykutSarac** [comment]
Hello, closing this issue as JSON Crack is intended to support graph visualization only for embedding.
