### ISSUE TITLE
[BUG]: Expand modes after collapsing

### ISSUE THREAD

**Issue by kalczugag** [AykutSarac/jsoncrack.com#386]
### Issue description

The bug faces when following steps:
1. View > Collapse Nodes
2. Expand by clicking icon button on tree

Now "Expand Nodes" is showing on view list and after clicking nothing happens because nodes are expanded.

### Media & Screenshots

![image](https://github.com/AykutSarac/jsoncrack.com/assets/99886900/c8e00551-d299-417e-8283-a7151adbb276)

### Operating system

- OS: [e.g. iOS]:
- Browser [e.g. chrome, safari]:

- Any other details...

### Priority this issue should have

Medium (should be fixed soon)

**Comment by AykutSarac** [comment]
Hi, there was an update shipped around that time. I've checked and it's working fine for me, can you check it again?

**Comment by kalczugag** [comment]
I have still the same problem, like there is no sync between view options and cell option.

**Comment by zoosphar** [comment]
Hey @kalczugag 
In the screenshot you provided not all the nodes are expanded, if you look carefully the "powers" nodes are not expanded and I've tried it on my system It's working as expected. Can you provide a screen recording if it's still not working on your side?

**Comment by zoosphar** [comment]
@AykutSarac One update on the UI side of the View Menu we can do is to change the text of the Menu Item from "Expand/Collapse Nodes" to "Expand/Collapse Graph" because it's toggling the whole graph and not particular nodes.
What do you think?

**Comment by AykutSarac** [comment]
> @AykutSarac One update on the UI side of the View Menu we can do is to change the text of the Menu Item from "Expand/Collapse Nodes" to "Expand/Collapse Graph" because it's toggling the whole graph and not particular nodes. What do you think?

Makes sense.

**Comment by zoosphar** [comment]
> > @AykutSarac One update on the UI side of the View Menu we can do is to change the text of the Menu Item from "Expand/Collapse Nodes" to "Expand/Collapse Graph" because it's toggling the whole graph and not particular nodes. What do you think?
> 
> Makes sense.

Opening a PR for the same
