### ISSUE TITLE
[BUG]: Zoom Label Not Updating After Selection or Input

### ISSUE THREAD

**Issue by Shahidullah-Muffakir** [AykutSarac/jsoncrack.com#388]
## Issue Summary

When a user enters the zooming amount in the input field or selects the zooming level from the dropdown (e.g., Zoom to 100%, Zoom to 50%), the label next to the zoom dropdown does not update to reflect the selected zoom level.

## Steps to Reproduce

1. Open the editor.
2. Click on the Zoom Menu in the top right corner.
3. Select any zooming level from the dropdown.
4. Alternatively, instead of step 3, enter a zooming value in the input field (e.g., 80).

## Expected Behavior

The label next to the zoom dropdown should correctly display the zooming level that the user has selected from the dropdown or entered in the input field.

## Actual Behavior

The label is not updating, and it remains unchanged after selecting a zooming level from the dropdown or entering a value in the input field.

### Media & Screenshots

![image](https://github.com/AykutSarac/jsoncrack.com/assets/105579118/77e2e1e7-fd0f-4cfb-bf30-b818fa9d408a)

### Operating system

- OS : Windows
- Browser : Chrome

### Priority this issue should have

High (immediate attention needed)

**Comment by Shahidullah-Muffakir** [comment]
I can work on this issue.

**Comment by AykutSarac** [comment]
> I can work on this issue.

That'd be awesome! Please be cautious about re-renderings.

**Comment by Shahidullah-Muffakir** [comment]
> > I can work on this issue.
> 
> That'd be awesome! Please be cautious about re-renderings.
Thanks! Sure, I'll keep that in mind.
