### ISSUE TITLE
[BUG]: Graph not rendering correctly from JSON

### ISSUE THREAD

**Issue by sandeepkumar-aitha** [AykutSarac/jsoncrack.com#396]
### Issue
When I try to display below JSON into graphical representation using https://jsoncrack.com/editor , it showing wrong representation.

`{
  "sys": {
    "type": "Array"
  },
  "pages": {},
  "limit": 100,
  "items": []
  }`

### Expected
"limit" is not root element and it should show along "sys", "pages" and "items".

### Media & Screenshots

![image](https://github.com/AykutSarac/jsoncrack.com/assets/29702836/f38769db-3f00-4f4e-8e76-9f35c6af109a)
![image](https://github.com/AykutSarac/jsoncrack.com/assets/29702836/1882cad3-6d86-4c75-bdd0-e5a392e2cfa4)

### Operating system

- OS: Windows 11
- Browser: Chrome

### Priority this issue should have

High (immediate attention needed)

**Comment by AykutSarac** [comment]
The parent nodes (array keys, object keys and objects) are always part of their parent nodes. This eliminates the need of creating an empty parent node and simplify the visualization.
