### ISSUE TITLE
[BUG]: The exported svg can only be viewed in the browser.

### ISSUE THREAD

**Issue by pommeJack** [AykutSarac/jsoncrack.com#397]
### Issue description

If I export it to a word document or use an online tool to convert it to png or other formats, I can only see a white transparent image.

### Operating system

- OS: [e.g. iOS]:
- Browser [e.g. chrome, safari]:
Edge
- Any other details...

### Priority this issue should have

Medium (should be fixed soon)

**Comment by AykutSarac** [comment]
SVG exports can be tricky sometimes, I recommend directly downloading PNG, JPEG versions when necessary.
