### ISSUE TITLE
[BUG]: unusual rendering

### ISSUE THREAD

**Issue by baradhili** [AykutSarac/jsoncrack.com#404]
### Issue description

this snippet shows as two children instead of one..
"investigations": [
{
"request": "are they good?",
"id": "ff18fd74-3357-4d63-85f1-958ca6d713cd",
"attachments": [],
"resultIssuedBy": "Test User"
}
]

Will update leter when I'm at my desk

### Operating system

- OS: [e.g. iOS]:
- Browser [e.g. chrome, safari]:

- Any other details...

### Priority this issue should have

Low (slightly annoying)

**Comment by AykutSarac** [comment]
It looks normal to me
![image](https://github.com/AykutSarac/jsoncrack.com/assets/47941171/95622beb-14b3-4045-9328-d5fe89b22c65)
