### ISSUE TITLE
[BUG]: pnpm build faild

### ISSUE THREAD

**Issue by kitmanten** [AykutSarac/jsoncrack.com#408]
### Issue description

> json-crack@v3.2.0 build /home/ubuntu/services/jsoncrack.com-3.2.0
> next build

- info Loaded env from /home/ubuntu/services/jsoncrack.com-3.2.0/.env.production
- info Linting and checking validity of types .Failed to compile.

./src/containers/Editor/JsonEditor/index.tsx:88:11
Type error: No overload matches this call.
  Overload 1 of 2, '(props: PolymorphicComponentProps<"web", FastOmit<{}, never>, void, void, {}, {}>): Element', gave the following error.
    Type '{ placeholder: string; value: string; onChange: (e: any) => void; rightSectionWidth: number; maxLength: number; disabled: boolean; onKeyDown: (event: React.KeyboardEvent<...> | KeyboardEvent) => void; onSubmit: () => Promise<...>; rightSection: Element; icon: Element; radius: number; }' is not assignable to type 'IntrinsicAttributes & FastOmit<Substitute<FastOmit<{}, never>, FastOmit<{}, never>>, keyof ExecutionProps> & FastOmit<...> & { ...; }'.
      Property 'placeholder' does not exist on type 'IntrinsicAttributes & FastOmit<Substitute<FastOmit<{}, never>, FastOmit<{}, never>>, keyof ExecutionProps> & FastOmit<...> & { ...; }'.
  Overload 2 of 2, '(props: FastOmit<{}, never>): ReactNode', gave the following error.
    Type '{ placeholder: string; value: string; onChange: (e: any) => void; rightSectionWidth: number; maxLength: number; disabled: boolean; onKeyDown: (event: React.KeyboardEvent<...> | KeyboardEvent) => void; onSubmit: () => Promise<...>; rightSection: Element; icon: Element; radius: number; }' is not assignable to type 'IntrinsicAttributes & FastOmit<{}, never>'.
      Property 'placeholder' does not exist on type 'IntrinsicAttributes & FastOmit<{}, never>'.

  86 |       <div>
  87 |         <StyledPromptInput
> 88 |           placeholder="Ask JSON Crack AI to transform the data"
     |           ^
  89 |           value={prompt}
  90 |           onChange={e => setPrompt(e.currentTarget.value)}
  91 |           rightSectionWidth={60}

### Operating system

- OS: [e.g. iOS] ubuntu 22.40
- Browser [e.g. chrome, safari]:

- Any other details...

### Priority this issue should have

Medium (should be fixed soon)

**Comment by AykutSarac** [comment]
Looks like old file structure to me, can you pull the repository then try again?
