### ISSUE TITLE
[BUG]: pnpm dev failed

### ISSUE THREAD

**Issue by ZukeDuex** [AykutSarac/jsoncrack.com#409]
### Issue description

Server Error appearing when opening http://localhost:3000/ in chrome:

Error: Cannot find package 'jsoncrack.com\node_modules\.pnpm\@mantine+core@7.11.2_@mantine+hooks@7.11.2_react@18.3.1__@types+react@18.2.51_react-dom@18.3._psiezpqe237cid5krnuc7pac5y\node_modules\react-remove-scroll\package.json' imported from jsoncrack.com\node_modules\.pnpm\@mantine+core@7.11.2_@mantine+hooks@7.11.2_react@18.3.1__@types+react@18.2.51_react-dom@18.3._psiezpqe237cid5krnuc7pac5y\node_modules\@mantine\core\esm\index.mjs
Did you mean to import "react-remove-scroll/dist/es5/index.js"?

This error happened while generating the page. Any console logs will be displayed in the terminal window.

### Operating system

- OS: [Windows 11]:
- Browser [Chrome]:
- Next.js (14.2.3)

### Priority this issue should have

Medium (should be fixed soon)

**Comment by AykutSarac** [comment]
Is this still relevant? What is the node version?
