### ISSUE TITLE
Can't get the docker image

### ISSUE THREAD

**Issue by wasfialzoubi** [AykutSarac/jsoncrack.com#424]
I tried to get the docker image and got the below error

C:\Windows\System32>docker build -t jsoncrack .
[+] Building 0.1s (1/1) FINISHED                                                                                                                                                              docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                                                                                                          0.0s
 => => transferring dockerfile: 2B                                                                                                                                                                            0.0s
ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory

C:\Windows\System32>docker build -t jsoncrack
ERROR: "docker buildx build" requires exactly 1 argument.
See 'docker buildx build --help'.

Usage:  docker buildx build [OPTIONS] PATH | URL | -

Start a build

**Comment by AykutSarac** [comment]
You're not at the repository folder, thus it cannot find the Dockerfile.

Closing this issue as it's not directly related to JSON Crack.
