### ISSUE TITLE
Is there a way to link one node to another by key?

### ISSUE THREAD

**Issue by DmitryLukyanov** [AykutSarac/jsoncrack.com#430]
### Feature

I wonder whether there is any way to connect one json node to another by key? Let's say there is a json like (actual hierarchy is much more complicated):

	{
		{ "Node" : "value1", "Key" : "key1", "Parent" : null },
		{ "Node" : "value2", "Key" : "key2", "Parent": "key1" }
	}

I want to have a reference/connection by `Key`/`Parent` fields between first and second nodes (a connection by key also may be between a node on the root level and another placed deep down in the nested nodes).

Any ideas how to do it?

**Comment by AykutSarac** [comment]
That'd be out of scope of JSON Crack, as the main purpose of the app to visualize data directly without requiring (or following) a schema.

**Comment by DmitryLukyanov** [comment]
I supposed so too.. I hoped some trick might be possible though.
