### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by YoYoFreakCJ** [AykutSarac/jsoncrack.com#432]
### Feature

I want to be able to search for values and property names.

Most of the time when analyzing JSON I'm looking whether a certain value or property is included for which I then want to find out the path. Hence I'd like a feature to search for values and property names. It could look like the default VS Code search feature which allows cycling through the results.

Listing all results in a new serach results section underneath the graph would also go a long way.

**Comment by paimagham** [comment]
I want to work on this

**Comment by AykutSarac** [comment]
You can search within the graph, I don't quite get what you mean by searching.

<img width="496" alt="image" src="https://github.com/user-attachments/assets/92bf5bb4-964a-4ebd-907f-1165f23b70df">
