### ISSUE TITLE
Property/Path Filter

### ISSUE THREAD

**Issue by YoYoFreakCJ** [AykutSarac/jsoncrack.com#433]
### Feature

I'd like a feature to filter for properties or paths.

When analyzing JSON I often want to look at values at specific paths. This is especially helpful with arrays.

### Example
Let's say I want to see all ages of a person array. The JSON input could look like this:

```json
[
  { "firstName": "Donald", "lastName": "Duck", "age": 30 },
  { "firstName": "Scrooge", "lastName": "McDuck", "age": 70 }
]
```

I'd then like to define a filter like `{Root}.[*].age` which should result in showing only the ages in the graph, while `firstName` and `lastName` will be omitted. If we want to be fancy we could then also show a hint that there are other properties which are hidden by the filter, and show those in a tooltip, or even show them upon clicking an "unhide" button.

**Comment by AykutSarac** [comment]
This exists already. Tools > JSON Query (JQ)
