### ISSUE TITLE
Allow the json contents to be sent via request parameters

### ISSUE THREAD

**Issue by juandari1979** [AykutSarac/jsoncrack.com#435]
### Feature

In the past with jsonvisio.com you could send the json contents in the json query parameter. jsoncrack seems to only accept a url as that parameter in order to get the json contents.

### Other context

Example:
https://jsoncrack.com/editor?json=%5B%5B%22squadName%22%2C%22homeTown%22%2C%22formed%22%2C%22a%7C0%7C1%7C2%22%2C%22Super%20hero%20squad%22%2C%22Metro%20City%22%2C%22n%7CWW%22%2C%22o%7C3%7C4%7C5%7C6%22%5D%2C%227%22%5D

**Comment by AykutSarac** [comment]
While it works with small JSON data, it fails to handle most JSON data due to the browser’s URL length limitation.
