### ISSUE TITLE
[BUG]: Attributes not displayed / incorrect sequence

### ISSUE THREAD

**Issue by DamianFekete** [AykutSarac/jsoncrack.com#441]
### Issue description

For the following input
```json
{
  "2": {
    "2-1": "2-1"
  },
  "3": "3",
  "4": [4],
  "5": "ipsum Excepteur aliquip"
}
```
4 appears to be connected to 3, and 5 is not displayed at all.

### Media & Screenshots

![image](https://github.com/user-attachments/assets/3b9f0bf6-6e96-4693-893a-89c5794a427c)

### Operating system

Firefox/Windows

### Priority this issue should have

Medium (should be fixed soon)

**Comment by AykutSarac** [comment]
Would you be able to try out the #431 locally and share your feedback?

**Comment by DamianFekete** [comment]
Hi @AykutSarac, it looks better with that one.

![image](https://github.com/user-attachments/assets/51e6304e-8d3a-49ed-a273-d42a286d6248)
