### ISSUE TITLE
[Bug] Nested arrays omit items

### ISSUE THREAD

**Issue by abrudz** [AykutSarac/jsoncrack.com#99]
```json
{
  "": [
    [
      2,
      7,
      1,
      2
    ]
  ]
}
```
gives:
![image](https://user-images.githubusercontent.com/10961427/187087536-1bfb10ab-916d-45cd-a0b0-525bb67761bb.png)
Note how elements 0 and 3 are missing.

**Comment by kaungsithar** [comment]
Could you please try again? It seems to be working now as expected. 

<img width="690" alt="image" src="https://user-images.githubusercontent.com/41876358/189545050-50fdd94e-aeb3-46d5-8c04-4e98f652dcbd.png">
